### ISSUE TITLE
Fatal error: exception JBasics.Class_structure_error("Illegal constant kind: 18")

### ISSUE THREAD

**Issue by crm416** [facebook/infer#286] opened 2016-02-24 07:18 UTC
Hey there.

I'm hoping to analyze our Android codebase with Infer, but have run into the aforementioned exception.

For context: we're currently using Java 8 in our codebase, made possible with [Retrolambda](https://github.com/orfjackal/retrolambda). I've seen the mentions in other issues (#249, #264, etc.) as to the lack of Java 8 support, so I imagine that this could be causing problems for Infer, though it's not entirely clear to me what the expected behavior should be with Retrolambda thrown into the mix, since, e.g., the post-Retrolambda'd bytecode should be Java 6-compatible.

Anyway--totally fine if the answer here is "We don't support Java 8, nor do we support Retrolambda'd bytecode".

Thanks in advance.

**Comment by akotulski** [comment] 2016-02-24 11:43
Does it mean that you use Java 8 without lambdas that ship with Java 8 (and use retrolambda for that)?
Unfortunately, if that's the case, you are still using Java 8 as far as infer is concerned.

That being said, I don't know what infer does for "Retrolambda'd  bytecode" in Java7 bytecode.

**Comment by jvillard** [comment] 2016-02-24 13:01
Also, we are waiting for an upstream fix that will allow infer not to crash on Java 8 bytecode. This should come soon. Infer will still skip files that use Java 8 in the short term, though.

**Comment by crm416** [comment] 2016-02-24 17:07
Thanks for the quick replies.

With Retrolambda, we write our code using a subset of Java 8 (we can use lambdas and method references, but no new APIs, for example), and Retrolambda then modifies the output bytecode to be Java 7-compatible.

So if Infer were determining a file's Java language level based on the output bytecode, I'd expect it to work on a codebase that was using Retrolambda? Alternatively, if Infer is skipping Java 8 files, isn't this error unexpected?

**Comment by akotulski** [comment] 2016-02-24 17:22
Is retrolambda modifying everything to be java 7 compatible or only gets rid of lambdas? I think we don't understand any of new Java 8 instructions not matter how small/easy to implement.

Infer is not skipping Java 8 files yet, but it will in near future. So it's still expected to happen

**Comment by crm416** [comment] 2016-02-25 01:10
> Infer is not skipping Java 8 files yet, but it will in near future.

Thanks for the clarification.

> Is retrolambda modifying everything to be java 7 compatible or only gets rid of lambdas?

It should be modifying everything to be Java 7-compatible, since Android dex-ing only supports Java 7.

**Comment by vicmosin** [comment] 2016-02-25 15:28
Does this thread means Infer doesn't support java 8?

**Comment by jvillard** [comment] 2016-02-25 15:48
@vicmosin here's a quick summary/clarification:

- current situation: infer crashes when it sees java 8-specific code (lambdas, ...)
- near future: infer skips files containing java 8-specific code
- one day: infer analyses and reports bugs on java 8 code

Note that this discussion is about java 8 features *in the code*. For instance, it's perfectly fine to take code that is compatible with java 7 (eg, anything targetting android), and compile it using java 8 to be analysed by infer.

In the context of this issue, if Infer catches the code after retrolambda has transformed it, then it shouldn't crash. @crm416: what steps are you using to analyse your project with retrolambda + infer?

**Comment by vicmosin** [comment] 2016-02-25 16:36
@jvillard thanks for fast response. so once again, near future - when it is approx? next week, next month?

**Comment by jvillard** [comment] 2016-02-25 16:41
Should be a couple of weeks. In the meantime, you can manually revert 6fa9b995e5404e1417e8f2fca6bfa9b98c095c47 to go back to the behaviour of infer skipping files containing java 8 bytecode. We disabled it because this may leak file descriptors, so if your project was large then infer could eventually fail by opening too many file descriptors.

**Comment by laalto** [comment] 2016-03-15 08:36
@jvillard Also here trying to run infer 0.7.0 on an Android codebase with retrolambda and getting this same error as @crm416 . Using [me.tatarka.retrolambda:3.2.5](https://github.com/evant/gradle-retrolambda) Gradle plugin with default settings, invoking infer with

    infer -- gradle assembleFlavornameDebug

**Comment by jvillard** [comment] 2016-03-17 13:29
@laalto thanks for the update!

We hope to have Java8 support in Infer at some point. Right now (v0.8.0), the situation should be that Infer skips Java8 files, not that it crashes.

If you can provide a way for us to reproduce your issue we'll look into it.

**Comment by crm416** [comment] 2016-03-20 20:40
@jvillard -- Sorry for the delay. Appreciate all the activity in this thread.

To analyze my project, I was just using the recommended flow: `infer -- ./gradlew assembleDebug`.

With Retrolambda in the mix, the Android build process is something like:

- Run `javac` over your source files to produce Java 8 bytecode.
- Retrolambda transforms the bytecode to be Java 6/7 compatible.
- `dx` transforms the transformed bytecode into a `.dex` file.

I believe that Infer relies on the `javac` output from the gradle build process (please correct me if I'm mistaken--certainly no expert here), so maybe the issue is that it's using the pre-transformed bytecode.

(I'll try to put together a minimal example.)

Two quick asides, though:

1. It's unclear to me if this is worth fixing right now, since I imagine that a lot will have to change with the introduction of [Jack](http://developer.android.com/preview/j8-jack.html) (already available in the N developer preview), which will make some Java 8 language features standard in Android (backwards compatible to Gingerbread) and will remove the `javac` step from the Android build process.
2. Not relevant to this particular issue, but... it's interesting to me that Infer operates on bytecode, yet it ties in so well with annotations, which (I believe?) are stripped out by the time you get to bytecode (again, please correct me if I'm wrong). Are there any resources around for learning more about how that works?

**Comment by crm416** [comment] 2016-03-20 21:05
Woo! I was actually able to run Infer over my project with `infer -- ./gradlew compileDebugJavaWithJavac` (or `infer -- ./gradlew assembleDebug`). It's successfully skipping over files with Java 8 language features.

Is this a result of the recent 0.8.0 release?

**Comment by jvillard** [comment] 2016-03-21 14:48
Thanks for the detailed update @crm416. Skipping Java 8 files and not crashing is the expected behaviour, there's a fix in 0.8.0 to reintroduce it.

For infer to be able to analyse code compiled with retrolambda, one of these two things needs to happen:
1. Java 8 support is added to Infer (#314)
2. Support for starting from the bytecode instead of from the Java source is added to Infer (#308)

1 is planned, and there's nothing stopping 2 in principle, since our Java frontend already starts from Java bytecode (only some rearchitecturing is needed to be able to not start from the sources).

I'm closing this issue since it's been resolved. Use the other two issues to track progress on the larger issue of dealing with Java8 bytecode.

**Closed by jvillard** 2016-03-21 14:48 UTC
