### ISSUE TITLE
build failed with ios app

### ISSUE THREAD

**Issue by zhangying19871987** [facebook/infer#458] opened 2016-09-08 02:26 UTC
/Users/selmazhang/workspace/house_ios_codeCheck/src/Classes/Crash/Base/QHCrashAsyncThread_current.S:16:1: error: expected
identifier or '('
.text
^
/Users/selmazhang/workspace/house_ios_codeCheck/src/Classes/Crash/Base/QHCrashAsyncThread_current.S:212:1: error: unknown
type name 'mov'
mov r7, sp
^
/Users/selmazhang/workspace/house_ios_codeCheck/src/Classes/Crash/Base/QHCrashAsyncThread_current.S:212:15: error: 
expected ';' after top level declarator
mov r7, sp
^
;
/Users/selmazhang/workspace/house_ios_codeCheck/src/Classes/Crash/Base/QHCrashAsyncThread_current.S:251:1: error: unknown
type name 'ldr'
ldr r1, [sp, #16];
^
/Users/selmazhang/workspace/house_ios_codeCheck/src/Classes/Crash/Base/QHCrashAsyncThread_current.S:251:14: error: use of
undeclared identifier 'sp'
ldr r1, [sp, #16];
^
/Users/selmazhang/workspace/house_ios_codeCheck/src/Classes/Crash/Base/QHCrashAsyncThread_current.S:251:13: error: 
expected identifier or '('
ldr r1, [sp, #16];
^
/Users/selmazhang/workspace/house_ios_codeCheck/src/Classes/Crash/Base/QHCrashAsyncThread_current.S:254:1: error: unknown
type name 'mov'
mov r2, sp
^
/Users/selmazhang/workspace/house_ios_codeCheck/src/Classes/Crash/Base/QHCrashAsyncThread_current.S:254:15: error: 
expected ';' after top level declarator
mov r2, sp
^
;
8 errors generated.
clang -cc1as: error: error reading '/var/folders/yt/mcn2wbd112g1pyjcn84h4c3h0000gn/T/QHCrashAsyncThread_current-e9c334.s'
Command /Users/selmazhang/workspace/infer-osx-v0.9.2/infer/lib/python/inferlib/../../../lib/xcode_wrappers/clang failed with exit code 1

** BUILD FAILED **

the full output of infer in 1.txt
[1.txt](https://github.com/facebook/infer/files/460719/1.txt)

**Comment by jeremydubreil** [comment] 2016-09-08 02:33
This looks like a compilation error and not directly related with the analysis. What build tool are you using to compile your project ? Do you get the failure with `infer <infer options> -- <build command>` whereas `<build command>` does not lead to compilation issues ?

**Comment by jeremydubreil** [comment] 2016-09-08 02:39
Is this report different from #450 ?

**Comment by akotulski** [comment] 2016-09-08 09:25
@jeremydubreil this is an issue with us trying to compile assembly code and fail. I've been unable to reproduce the problem so far.
Closing this one as this is duplicate of #450

**Closed by akotulski** 2016-09-08 09:25 UTC
