### ISSUE TITLE
Nothing to analyze when run the infer android_hello example

### ISSUE THREAD

**Issue by gangji001** [facebook/infer#66] opened 2015-06-16 06:04 UTC
do not modify the code but the infer does not analyze the problem of android_hello project.

jigangdeiMac:android_hello jigang$ infer -- ./gradlew build
13:59:53.027 [ERROR] [org.gradle.api.Project] /Users/jigang/infer-osx-v0.1.0/infer/examples/android_hello/app/build/intermediates/exploded-aar/com.android.support/appcompat-v7/22.0.0/res/drawable-hdpi-v4/abc_spinner_mtrl_am_alpha.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
14:00:03.625 [ERROR] [org.gradle.api.Project] /Users/jigang/infer-osx-v0.1.0/infer/examples/android_hello/app/build/intermediates/exploded-aar/com.android.support/appcompat-v7/22.0.0/res/drawable-hdpi-v4/abc_spinner_mtrl_am_alpha.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
TODO: print error message
TODO: print error message
There was nothing to analyze, exiting
jigangdeiMac:android_hello jigang$

**Comment by MrThiago** [comment] 2015-06-16 06:28
try to run ./gradlew clean first.

**Comment by martinoluca** [comment] 2015-06-16 07:47
Hello @gangji001, can you also please tell us which version of `javac` you are currently using?
Simply run `javac -version` on your terminal.
Thanks!

**Comment by gangji001** [comment] 2015-06-16 11:21
jre version jdk1.7.0_71.jdk.  and I have another problem.

when i run infer -- javac Hello.java in example folder, the error raised:

jigangdeiMac:examples jigang$ infer -- javac Hello.java 
TODO: print error message
Starting analysis (Infer version v0.1.0)
Fatal error: exception Sys_error("/Users/jigang/infer-osx-v0.1.0/infer/examples/infer-out/captured: No such file or directory")
[ERROR] Failure during create_makefile, original command was

[u'inferJ', u'-g', u'-a', 'infer', u'javac', 'Hello.java']


Traceback (most recent call last):
  File "/Users/jigang/infer-osx-v0.1.0/infer/infer/bin/inferJ", line 19, in <module>
    stats = analysis.start()
  File "/Users/jigang/infer-osx-v0.1.0/infer/infer/bin/inferlib.py", line 634, in start
    self.analyze_and_report()
  File "/Users/jigang/infer-osx-v0.1.0/infer/infer/bin/inferlib.py", line 613, in analyze_and_report
    if self.analyze() == os.EX_OK:
  File "/Users/jigang/infer-osx-v0.1.0/infer/infer/bin/inferlib.py", line 489, in analyze
    self.args.analyzer
  File "/Users/jigang/infer-osx-v0.1.0/infer/infer/bin/inferlib.py", line 318, in run_command
    raise e
subprocess.CalledProcessError: Command '[u'/Users/jigang/infer-osx-v0.1.0/infer/infer/bin/InferAnalyze', u'-results_dir', '/Users/jigang/infer-osx-v0.1.0/infer/examples/infer-out', u'-makefile', u'Makefile', u'-allow_specs_cleanup', u'-models', u'/Users/jigang/infer-osx-v0.1.0/infer/infer/bin/../lib/java/models.jar', u'-project_root', '/Users/jigang/infer-osx-v0.1.0/infer/examples']' returned non-zero exit status 2

**Comment by gangji001** [comment] 2015-06-16 11:23
I did clean and incremental build, There was nothing to analyze again.

jigangdeiMac:android_hello jigang$ ./gradlew clean
:app:clean

BUILD SUCCESSFUL

Total time: 1 mins 48.317 secs
jigangdeiMac:android_hello jigang$ infer --incremental -- ./gradlew build
19:21:00.825 [ERROR] [org.gradle.api.Project] /Users/jigang/infer-osx-v0.1.0/infer/examples/android_hello/app/build/intermediates/exploded-aar/com.android.support/appcompat-v7/22.0.0/res/drawable-hdpi-v4/abc_spinner_mtrl_am_alpha.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
19:21:12.434 [ERROR] [org.gradle.api.Project] /Users/jigang/infer-osx-v0.1.0/infer/examples/android_hello/app/build/intermediates/exploded-aar/com.android.support/appcompat-v7/22.0.0/res/drawable-hdpi-v4/abc_spinner_mtrl_am_alpha.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
TODO: print error message
TODO: print error message
There was nothing to analyze, exiting
jigangdeiMac:android_hello jigang$

**Comment by sblackshear** [comment] 2015-06-19 00:41
Hi @gangji001. Would you mind trying out the 0.1.1 release and seeing if it fixes the problem?

**Comment by jvillard** [comment] 2015-06-22 14:45
The first issue seems to be a duplicate of #18. We are working on a fix.

Your second issue seems to be a duplicate of #30. The temporary workaround is to install java and javac version 1.7.

I am closing this issue as #18 and #30 seem to cover it. Feel free to re-open if you don't think this is the case.

**Closed by jvillard** 2015-06-22 14:45 UTC
