### ISSUE TITLE
False positive related to a File object in Java - Null Dereference

### ISSUE THREAD

**Issue by xennygrimmato** [facebook/infer#624] opened 2017-03-20 09:08 UTC
A bug was reported by Infer for the following code snippet:

```java
File srcFile = new File(...);
...
if (!srcFile.delete()) {
    System.out.println("Cannot delete file " + srcFile);
}
```

The qualifier for the issue says: ```object returned by srcFile.delete() could be null and is dereferenced at line 88```. srcFile gets initialized and is not null.

In Java's `File` class, the `delete` method returns `boolean`. It can not return `null`.
I think this is a false positive.

**Comment by sblackshear** [comment] 2017-03-20 22:55
I can't reproduce this on master. I'm using the following code:

```
import java.io.File;

public class Test {
  void foo() {
    File srcFile = new File("");
    if (!srcFile.delete()) {
      System.out.println("Cannot delete file " + srcFile);
    }
  }
}
```

Infer reports nothing on this code. Is there something different about your example?

**Comment by sblackshear** [comment] 2017-04-19 23:39
Optimistically closing; let me know if you have find a self-contained repro and I will try it.

**Closed by sblackshear** 2017-04-19 23:39 UTC
