### ISSUE TITLE
Can't build infer

### ISSUE THREAD

**Issue by GUIpsp** [facebook/infer#1030] opened 2018-12-12 16:19 UTC
Git commit:
61b51b09dba6be61901ee1d21d90ac02265db3c8

Opam version:
`2.0.1`

Command:
`./build-infer.sh java`

Log (has escape codes, curl it to a terminal to view it properly):
http://sprunge.us/0oOSD6

I don't usually use OCaml, so please let me know if there is any more info I can provide.

**Comment by GUIpsp** [comment] 2018-12-12 16:52
Also, travis always builds from docker, and docker always builds a release version. Not sure if this is intended or not.

**Comment by jvillard** [comment] 2018-12-12 17:04
The version of javalib that is installed is too new, you need to manually downgrade to 2.3.5 due to this issue: https://github.com/ocaml/opam/issues/3694

If you start from an empty ~/.opam it shouldn't happen.

To manually downgrade: `opam install javalib.2.3.5`. Beware that you need to disable opam sandboxing due to this other issue: https://github.com/ocaml/opam-repository/issues/13040

You can disable sandboxing by editing ~/.opam/config and removing the last 6 lines (sometimes 3) about `wrap-*-commands`.

**Comment by GUIpsp** [comment] 2018-12-12 18:04
> If you start from an empty ~/.opam it shouldn't happen.

I started from a fresh ubuntu VM and that's the version the build script installed for me. I just deleted the opam directory, and tried again, and it picked the 3.0 version too.

> To manually downgrade: `opam install javalib.2.3.5`. Beware that you need to disable opam sandboxing due to this other issue: [ocaml/opam-repository#13040](https://github.com/ocaml/opam-repository/issues/13040)
> 
> You can disable sandboxing by editing ~/.opam/config and removing the last 6 lines (sometimes 3) about `wrap-*-commands`.

This worked to fix my issue, but possibly the build script should do this automatically? (Atleast the pinning).

Also, the build notes point to travis for help, which doesn't really help when travis is building old versions.


Thanks for the help! Should I leave this open (for the travis issue, or the pinning issue) or close it?

**Comment by jvillard** [comment] 2018-12-13 13:52
I just pushed d468e22e666030a7f3c6284ace6e17b34646272e which should address most of the build quirks as they had been fixed upstream.

> This worked to fix my issue, but possibly the build script should do this automatically? (Atleast the pinning).

That's what it is trying to do by using `opam --locked` but it doesn't work as intended because of ocaml/opam#3694. The latest master doesn't need the sandboxing tricks anymore, and running `opam install --deps-only infer .` should work. Maybe the build script should do this to circumvent the issue with opam while we wait for it to be fixed.

> Also, the build notes point to travis for help, which doesn't really help when travis is building old versions.

The osx travis builds master though.

Feel free to close this issue as I think d468e22e666030a7f3c6284ace6e17b34646272e addresses the main pain points.

**Closed** 2018-12-13 16:35 UTC
