### ISSUE TITLE
[ERROR] Failure during analysis, original command was

### ISSUE THREAD

**Issue by juneJuly** [facebook/infer#65] opened 2015-06-16 01:54 UTC
TODO: print error message
Starting analysis (Infer version git-17f0b5cbe2a1d4dd5831c79ce43bdb6c0e5da230)
Fatal error: exception Sys_error("/workspace_ios/infer/infer/models/java/models/infer/captured: No such file or directory")
[ERROR] Failure during analysis, original command was
.........
.........
Traceback (most recent call last):
  File "/workspace_ios/infer/infer/models/java/../../bin/inferJ", line 19, in <module>
    stats = analysis.start()
  File "/Users/june/work/workspace_ios/infer/infer/bin/inferlib.py", line 634, in start
    self.analyze_and_report()
  File "/workspace_ios/infer/infer/bin/inferlib.py", line 613, in analyze_and_report
    if self.analyze() == os.EX_OK:
  File "/workspace_ios/infer/infer/bin/inferlib.py", line 466, in analyze
    self.args.analyzer
  File "/workspace_ios/infer/infer/bin/inferlib.py", line 318, in run_command
    raise e
subprocess.CalledProcessError: Command '[u'//workspace_ios/infer/infer/bin/InferAnalyze', u'-results_dir', u'/workspace_ios/infer/infer/models/java/models/infer', u'-allow_specs_cleanup', u'-project_root', '/workspace_ios/infer/infer/models/java', u'-java', u'-ziplib', '/workspace_ios/infer/dependencies/java/jackson/jackson-2.2.3.jar']' returned non-zero exit status 2
make[2]: *** [/workspace_ios/infer/infer/models/java/models/infer/report.csv] Error 1
make[1]: *** [../lib/java/models.jar] Error 2
make: *** [java] Error 2

really make me crazy...

**Comment by juneJuly** [comment] 2015-06-17 01:18
23:59:23.831 [ERROR] [org.gradle.api.Project] /workspace_ios/infer/examples/android_hello/app/build/intermediates/exploded-aar/com.android.support/appcompat-v7/22.0.0/res/drawable-hdpi-v4/abc_spinner_mtrl_am_alpha.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
23:59:34.151 [ERROR] [org.gradle.api.Project] /workspace_ios/infer/examples/android_hello/app/build/intermediates/exploded-aar/com.android.support/appcompat-v7/22.0.0/res/drawable-hdpi-v4/abc_spinner_mtrl_am_alpha.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
Fatal error: exception Failure("Java model file is required")
[ERROR] Failure during frontend, original command was


does infer treat all warnings as errors ?
"libpng warning: iCCP: Not recognizing known sRGB profile that has been edited"  this is just a warning caused by android build tool 21.0.1 and 22.0.1

**Comment by jeremydubreil** [comment] 2015-06-17 07:12
@juneJuly: thanks for reporting this. According to this error message: `TODO: print error message` at the beginning of the logs, the failure seems to be caused by a failure in the library parsing the bytecode. We are working on this and trying to push the fix upstream.

The second error seems unrelated. Infer normally use the same `javac` compilation command than in the original compilation, so do not change the warning as error aspect. Do you know if could reproduce this issue on a small example ?

**Comment by juneJuly** [comment] 2015-06-17 07:39
@jeremydubreil:  the second error :  i just use the 'android_hello' project at path /infer/examples/android_hello

when i use infer -- javac Hello.java,i got an error as below:

xxxxMacBook-Pro:examples june$ pwd
/workspace_ios/infer/examples

xxxxMacBook-Pro:examples june$ infer -- javac Hello.java 
Fatal error: exception Failure("Java model file is required")
[ERROR] Failure during frontend, original command was

[u'inferJ', u'-g', u'-a', 'infer', u'javac', 'Hello.java']


Traceback (most recent call last):
  File "/workspace_ios/infer/infer/bin/inferJ", line 19, in <module>
    stats = analysis.start()
  File "/workspace_ios/infer/infer/bin/inferlib.py", line 632, in start
    if self.capture() == os.EX_OK:
  File "/workspace_ios/infer/infer/bin/inferlib.py", line 400, in capture
    return self.run_infer_frontend()
  File "/workspace_ios/infer/infer/bin/inferlib.py", line 391, in run_infer_frontend
    self.args.analyzer
  File "/workspace_ios/infer/infer/bin/inferlib.py", line 318, in run_command
    raise e
subprocess.CalledProcessError: Command '[u'/workspace_ios/infer/infer/bin/InferJava', u'-results_dir', '/workspace_ios/infer/examples/infer-out', u'-verbose_out', '/var/folders/z_/5zmq3f8x7cbbnf_sw07p84s00000gn/T/javac_ilYQcZ.out', u'-no-static_final']' returned non-zero exit status 2


dows that means my env is not right?

**Comment by jeremydubreil** [comment] 2015-06-17 14:44
@juneJuly: no, the issue is in Infer. This is an issue in the thrid-party libraries used to parse bytecode and we are working on pushing a fix upstream. However, we have not been able to reproduce it locally.

**Comment by juneJuly** [comment] 2015-06-17 16:09
@jeremydubreil: thanks a lot, can u push me a msg when u fix it?  and is there anything i can do?

**Comment by chuanshao** [comment] 2015-06-22 11:36
@juneJuly @jeremydubreil I hava the same error when I run  infer -- javac Hello.java . i don't know how to fix it.

**Comment by jvillard** [comment] 2015-06-22 14:43
@juneJuly: Your first issue seems to be a duplicate of #30. The temporary workaround is to install java and javac version 1.7. @chuanshao, please try this as well.

Your second issue seems to be a duplicate of #18. We are working on a fix.

I am closing this taks as #18 and #30 seem to cover the same issues. Feel free to re-open if you don't think this is the case.

**Closed by jvillard** 2015-06-22 14:43 UTC

**Comment by juneJuly** [comment] 2015-06-24 01:41
@jvillard 
my java version:
xxxxMacBook-Pro:~ june$ java -fullversion
java full version "1.7.0_60-b19"

and "javac Hello.java" work well

thanks a lot

**Comment by jvillard** [comment] 2015-07-02 12:27
@juneJuly There is a chance that 82c4dc6d104a6643f5433c440e74b0699b7e05bf solves your issue. Please upgrade Infer to the latest git version and let me know if the issue is still there. Thanks!

**Comment by juneJuly** [comment] 2015-07-08 03:06
@jvillard yes,this worked for me. thz!
