### ISSUE TITLE
Statically linked binaries for Linux

### ISSUE THREAD

**Issue by martinschaef** [facebook/infer#918] opened 2018-05-16 21:37 UTC
Hey, I want to integrate Infer with our build system, but for various reasons, I cannot build it from source easily (mostly license issues), and installing it with brew/apt-get is also not possible. Is there a way to get a binary blob as part of the release that I could just run on my x64 linux?

**Comment by jvillard** [comment] 2018-05-17 09:25
This seems like a duplicate of #470 

See [this comment](https://github.com/facebook/infer/issues/470#issuecomment-265168992) in particular. Please comment there if you have further questions, thanks!

**Closed by jvillard** 2018-05-17 09:25 UTC
