### ISSUE TITLE
About "ERADICATE_NULL_METHOD_CALL"

### ISSUE THREAD

**Issue by chen881129** [facebook/infer#383] opened 2016-06-15 07:04 UTC
Here is my code:

```
RankDocInfo doc = outResult.get(i);
String docvrid = doc.getClassid();
if (! docvrid.equals("xxx")) {
    .....
}
```

I wish to get an "ERADICATE_NULL_METHOD_CALL" when `docvrid`calls `equals()` method, but infer didn't.

**Comment by cristianoc** [comment] 2016-06-15 07:39
@chen881129 I guess you're using eradicate mode with `-a eradicate`.
Is the return type of `getClassid()` annotated `@Nullable`?

**Comment by chen881129** [comment] 2016-06-15 08:38
@cristianoc . Yeah, I used eradicate mode.
There is no error about `getClassid() may return null but it is not annotated with `@Nullable`` in the bug.txt.

**Comment by cristianoc** [comment] 2016-06-15 08:43
@chen881129 you should annotate `getClassid()` in your source code, e.g.
``` @Nullable String getClassid() { ... }```

**Comment by chen881129** [comment] 2016-06-15 10:06
@cristianoc In fact, I'm QA, I can't modify the code...
Thank you very much. I've seen the doc of Infer "What is the @Nullable convention?If you say nothing, you’re saying that the value **cannot be null**."

Can I modify the code of Infer to the opposite--If you say nothing, you’re saying that the value **can be null**."?

**Comment by chen881129** [comment] 2016-06-20 03:17
Hi, @cristianoc , I'm trying to find the code, could you give me some clue?

**Comment by sblackshear** [comment] 2016-07-06 16:14
@chen881129,
  Is your copy of the code read-only, or is it possible to change it locally just for testing? Or can you suggest that someone else add the `@Nullable` annotation? This seems like it would be the simplest solution.

It would be quite difficult to change Eradicate to treat all values as potentially nullable, but it should be fairly easy to modify Infer to do this. If you change the code [here](https://github.com/facebook/infer/blob/master/infer/src/backend/rearrange.ml#L1144) to 

```
let is_only_pt_by_nullable_fld_or_param _deref_exp =
  nullable_obj_str := "everything is null";
  true 
```
and delete lines 1145-1184, Infer should warn on ever deref unless it can prove the value being dereferenced is non-null.

**Comment by chen881129** [comment] 2016-08-26 03:06
@sblackshear .Sorry to trouble you again. Infer compile failed until the OS is updated to centos7. I modify  infer/src/backend/rearrange.ml as you said, but it comes an error: 
```
File "backend/rearrange.ml", line 1188, characters 2-5:
Error: Syntax error
Command exited with code 2.
```
Infer: v0.9.2
Now my code is like this:
```
  let is_only_pt_by_nullable_fld_or_param _deref_exp =
    nullable_obj_str := "everything is null";
    true
  let root = Exp.root_of_lexp lexp in
```
Can you help me ?

**Comment by sblackshear** [comment] 2016-08-26 03:19
Look's like you're missing an `in`: 

  let is_only_pt_by_nullable_fld_or_param _deref_exp =
    nullable_obj_str := "everything is null";
    true in
  let root = Exp.root_of_lexp lexp in

**Comment by chen881129** [comment] 2016-08-29 09:12
@sblackshear Thank you very much, but it still compile error...
```
File "backend/rearrange.ml", line 1186, characters 24-44:
Error: This expression has type string but an expression was expected of type
         'a option
Command exited with code 2.
```

backend/rearrange.ml line 1186 is:
```
1184   (* return true if deref_exp is only pointed to by fields/params with @Nullable annotations *)
1185   let is_only_pt_by_nullable_fld_or_param _deref_exp =
1186     **nullable_obj_str := "everything is null";**
1187     true in
1188   let root = Exp.root_of_lexp lexp in
```

**Comment by jvillard** [comment] 2016-08-29 18:52
Here the compiler is telling you that `"everything is null"` is a string but it was expecting some option type. You probably want `Some "everything is null"` instead.

For questions about OCaml it would be better to go to OCaml-specific resources:
http://ocaml.org/community/
irc://irc.freenode.net/#ocaml

**Comment by jvillard** [comment] 2018-06-05 12:41
Closing as eradicate is working as intended here if I understand correctly.

**Closed by jvillard** 2018-06-05 12:41 UTC
