### ISSUE TITLE
[objective-c]false-positive -dataWithBytesNoCopy-freeWhenDone:YES

### ISSUE THREAD

**Issue by GeekMin** [facebook/infer#104] opened 2015-06-25 01:49 UTC
+ (instancetype)dataWithBytesNoCopy:(void *)bytes
                             length:(NSUInteger)length
                       freeWhenDone:(BOOL)freeWhenDone
 NSData *imgData = [NSData dataWithBytesNoCopy:buffer length:dataLength freeWhenDone:YES];
"u know, if yes, the returned object takes ownership of the bytes pointer and frees it on deallocation."
&& I am using ARC.. memory leak here? no, i do not think so..but tool gives me the waring...
how can I do for this? thx buddy~

**Comment by dulmarod** [comment] 2015-06-25 09:39
Duplicate of #52. Please, take a look at the explanation there. This is a real bug.

**Closed by dulmarod** 2015-06-25 09:39 UTC
Labels: duplicate, objective-c
