### ISSUE TITLE
Infer reports inaccurate errors when there are classes with the same name in different packages.

### ISSUE THREAD

**Issue by tonycosentini** [facebook/infer#217] opened 2015-12-12 00:38 UTC
If I create two classes with the same class name, but in different packages Infer will inaccruately report warnings.

For example, if I have `com.example.inferbug.app.failing.MainActivity`:
```java
package com.example.inferbug.app.failing;

import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;

import com.example.inferbug.app.R;

import java.util.HashMap;

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        nonNullParameter(null);
    }

    //This method has the potential to be null dereferenced, as a null is passed into it.
    //To resolve warning we have to annotate the member with @Nullable, and surround its call with != null.
    public void nonNullParameter(HashMap<String, Object> mapThatShouldNotBeNull) {
        mapThatShouldNotBeNull.clear();
    }
}
```

and `com.example.inferbug.app.passing.MainActivity`:
```java
package com.example.inferbug.app.passing;

import android.os.Bundle;
import android.support.annotation.Nullable;
import android.support.v7.app.AppCompatActivity;

import com.example.inferbug.app.R;

import java.util.HashMap;

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        nonNullParameter(null);
    }

    //This method has the potential to be null dereferenced, as a null is passed into it.
    //To resolve warning we have to annotate the member with @Nullable, and surround its call with != null.
    public void nonNullParameter(@Nullable HashMap<String, Object> mapThatShouldNotBeNull) {
        if (mapThatShouldNotBeNull != null) {
            mapThatShouldNotBeNull.clear();
        }
    }
}
```

Running Infer will give me a warning for the class that should not have any warnings, also the warning points to a line that does not make any sense:
```
➜  InferBug  infer -- ./gradlew clean assembleDebug
Running and capturing gradle compilation...
Starting analysis (Infer version git-6d9c5c684ebeeca8a1af337200a56b836ea27f2a)
Computing dependencies... 100%
Analyzing 3 clusters...0%
Analyzed 38 procedures in 3 files

Found 1 issue
app/src/main/java/com/example/inferbug/app/passing/MainActivity.java:18: error: NULL_DEREFERENCE
  object null could be null and is dereferenced by call to nonNullParameter(...) at line 18
  16.           setContentView(R.layout.activity_main);
  17.           nonNullParameter(null);
  18. >     }
  19.
  20.       //This method has the potential to be null dereferenced, as a null is passed into it.
```

Attached is a zip file with the example I mentioned.

[InferBug.zip](https://github.com/facebook/infer/files/59989/InferBug.zip)

**Comment by jeremydubreil** [comment] 2015-12-15 00:03
Thanks for reporting this. We found out what the cause is and we are working on a fix.

**Comment by jeremydubreil** [comment] 2015-12-18 02:51
Should be fixed by https://github.com/facebook/infer/commit/d579b2be519647c559f90e140b888735829e381c.

**Closed by jeremydubreil** 2015-12-18 02:51 UTC

**Comment by tonycosentini** [comment] 2015-12-22 17:01
Awesome, thanks!
