### ISSUE TITLE
infer -E doesn't behave like gcc or clang causing some configure to fail

### ISSUE THREAD

**Issue by sylvestre** [facebook/infer#859] opened 2018-02-05 11:19 UTC
Firefox build system is performing some checks using -E and verifies the output.

With foo.c
```
#if __STDC_VERSION__
%STDC_VERSION __STDC_VERSION__
#endif

```
```
$ clang -E foo.c 
# 1 "foo.c"
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 349 "<built-in>" 3
# 1 "<command line>" 1
# 1 "<built-in>" 2
# 1 "foo.c" 2

%STDC_VERSION 201112L

```
With infer:
```
$ /home/sylvestre/dev/mozilla/infer/infer/lib/wrappers/clang -E foo.c 
Capturing in make/cc mode...

```

**Comment by jvillard** [comment] 2018-02-06 16:04
Thanks for the report, I'll see if I can make infer behave more like clang in this case. This looks like a duplicate of #696, let's discuss there.

**Closed by jvillard** 2018-02-06 16:04 UTC
