### ISSUE TITLE
build failed - clang: error: unknown argument: '-mwatchos-simulator-version-min=2.0'

### ISSUE THREAD

**Issue by sulthana** [facebook/infer#202] opened 2015-11-20 09:55 UTC
I am trying to use infer on Apple watch app to find possible crashes and errors. The command that I am using is like below,
"infer -- xcodebuild -target TestApp -configuration Debug -destination "name=iPhone5" -sdk watchsimulator2.0"

but the build is getting failed throwing error,
clang: error: unknown argument: '-mwatchos-simulator-version-min=2.0'

Please help me in getting rid of this issue.

Thanks in advance!

**Comment by jvillard** [comment] 2015-11-20 11:56
@sulthana, @martinoluca, is this a duplicate of #203?

**Comment by sulthana** [comment] 2015-11-20 12:09
@jvillard, Its not the duplicate. This is the alternate command that I tried to run Watchkit extension as a separate component Which returns the above mentioned error. I wanted to know the reason for the error and solution for the same. Please help me by giving info.

**Comment by jvillard** [comment] 2015-11-24 13:23
@sulthana one thing you can do is use infer on a target that does not use the watch toolkit, as infer's version of clang does not support it yet.

That said, you may have better luck with Infer's latest master, as we just upgraded clang to the latest trunk: 04e4546a918c0aa2d1a7331c7497578bfd1e149c

Note that you'll have to recompile infer's clang for this version (see instructions [here](https://github.com/facebook/infer/blob/master/INSTALL.md#compile-infer-from-source-with-clang-enabled)).

**Comment by jvillard** [comment] 2016-04-25 16:52
It seems that the version of clang used in Infer since [0.8.1](https://github.com/facebook/infer/releases/v0.8.1) supports the flags used to compile Watch apps. Please try the latest version of Infer on your project and re-open this issue if it still doesn't work. Thanks!

**Closed by jvillard** 2016-04-25 16:52 UTC
