### ISSUE TITLE
examples error

### ISSUE THREAD

**Issue by fulingfan** [facebook/infer#71] opened 2015-06-16 12:38 UTC
fulingfan@fulingfandeMacBook-Pro examples$ infer -- javac Hello.java 
TODO: print error message
Starting analysis (Infer version v0.1.0)
Fatal error: exception Sys_error("/Users/fulingfan/Documents/infer-osx-v0.1.0/infer/examples/infer-out/captured: No such file or directory")
[ERROR] Failure during create_makefile, original command was

[u'inferJ', u'-g', u'-a', 'infer', u'javac', 'Hello.java']

Traceback (most recent call last):
  File "/Users/fulingfan/Documents/infer-osx-v0.1.0/infer/infer/bin/inferJ", line 19, in <module>
    stats = analysis.start()
  File "/Users/fulingfan/Documents/infer-osx-v0.1.0/infer/infer/bin/inferlib.py", line 634, in start
    self.analyze_and_report()
  File "/Users/fulingfan/Documents/infer-osx-v0.1.0/infer/infer/bin/inferlib.py", line 613, in analyze_and_report
    if self.analyze() == os.EX_OK:
  File "/Users/fulingfan/Documents/infer-osx-v0.1.0/infer/infer/bin/inferlib.py", line 489, in analyze
    self.args.analyzer
  File "/Users/fulingfan/Documents/infer-osx-v0.1.0/infer/infer/bin/inferlib.py", line 318, in run_command
    raise e
subprocess.CalledProcessError: Command '[u'/Users/fulingfan/Documents/infer-osx-v0.1.0/infer/infer/bin/InferAnalyze', u'-results_dir', '/Users/fulingfan/Documents/infer-osx-v0.1.0/infer/examples/infer-out', u'-makefile', u'Makefile', u'-allow_specs_cleanup', u'-models', u'/Users/fulingfan/Documents/infer-osx-v0.1.0/infer/infer/bin/../lib/java/models.jar', u'-project_root', '/Users/fulingfan/Documents/infer-osx-v0.1.0/infer/examples']' returned non-zero exit status 2

**Comment by fulingfan** [comment] 2015-06-16 12:42
fulingfan@fulingfandeMacBook-Pro examples$ java -version
java version "1.7.0_71"
Java(TM) SE Runtime Environment (build 1.7.0_71-b14)
Java HotSpot(TM) 64-Bit Server VM (build 24.71-b01, mixed mode)

**Comment by ghguy** [comment] 2015-06-16 21:04
Try to install JDK 1.7. For example:

brew cask install caskroom/versions/java7

After that, try to run infer again. Good luck!

**Comment by jvillard** [comment] 2015-06-22 14:46
Closing as duplicate of #30.

**Closed by jvillard** 2015-06-22 14:46 UTC
