### ISSUE TITLE
Fatal error: exception Sys_error

### ISSUE THREAD

**Issue by monkeytest15** [facebook/infer#55] opened 2015-06-14 17:48 UTC
I use the infer to analysis the java file, but I get this info
```shell
TODO: print error message
Starting analysis (Infer version v0.1.0)
Fatal error: exception Sys_error("/Users/monkey/Documents/open_source/infer/examples/infer-out/captured: No such file or directory")
[ERROR] Failure during create_makefile, original command was

[u'inferJ', u'-g', u'-a', 'infer', u'javac', 'Hello.java']


Traceback (most recent call last):
  File "/Users/monkey/Documents/dev_tool/infer-osx-v0.1.0/infer/infer/bin/inferJ", line 19, in <module>
    stats = analysis.start()
  File "/Users/monkey/Documents/dev_tool/infer-osx-v0.1.0/infer/infer/bin/inferlib.py", line 634, in start
    self.analyze_and_report()
  File "/Users/monkey/Documents/dev_tool/infer-osx-v0.1.0/infer/infer/bin/inferlib.py", line 613, in analyze_and_report
    if self.analyze() == os.EX_OK:
  File "/Users/monkey/Documents/dev_tool/infer-osx-v0.1.0/infer/infer/bin/inferlib.py", line 489, in analyze
    self.args.analyzer
  File "/Users/monkey/Documents/dev_tool/infer-osx-v0.1.0/infer/infer/bin/inferlib.py", line 318, in run_command
    raise e
subprocess.CalledProcessError: Command '[u'/Users/monkey/Documents/dev_tool/infer-osx-v0.1.0/infer/infer/bin/InferAnalyze', u'-results_dir', '/Users/monkey/Documents/open_source/infer/examples/infer-out', u'-makefile', u'Makefile', u'-allow_specs_cleanup', u'-models', u'/Users/monkey/Documents/dev_tool/infer-osx-v0.1.0/infer/infer/bin/../lib/java/models.jar', u'-project_root', '/Users/monkey/Documents/open_source/infer/examples']' returned non-zero exit status 2
```

My java version is 1.7, python version is 2.7.

**Comment by jeremydubreil** [comment] 2015-06-14 20:24
@monkeytest15: thanks for reporting this. It seems that several people have experienced the same issue coming a failure in the library we use to parse bytecode. We are working on fixing the issue upstream.

**Comment by martinoluca** [comment] 2015-06-15 08:20
@monkeytest15 can you please provide the exact version of `javac` you have? Simply run `javac -version`
Thanks!

**Comment by hansi100** [comment] 2015-06-15 09:04
Hi, I met the same error.  My java version is 1.6

**Comment by houlianpi** [comment] 2015-06-16 01:59
$ java -version
java version "1.7.0_65"
Java(TM) SE Runtime Environment (build 1.7.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 24.65-b04, mixed mode)

same problem.

**Comment by jvillard** [comment] 2015-06-22 14:31
Closing as probable duplicate of #30. Feel free to re-open if you think that's not the case.

**Closed by jvillard** 2015-06-22 14:31 UTC
