### ISSUE TITLE
Unable to find build-infer.sh in the infer symbolink file while installing the infer with Docker

### ISSUE THREAD

**Issue by venkatn087** [facebook/infer#1461] opened 2021-06-25 12:26 UTC
Please make sure your issue is not addressed in the [FAQ](https://fbinfer.com/docs/support#troubleshooting).

Please include the following information:
- [ ] The version of infer from `infer --version`. I am trying to install inferV1.10 with the help of Docker.
- [ ] Your operating system and version, for example "Debian 9", "MacOS High Sierra", whether you are using Docker, etc. Yes We are Docker  and Docker version 20.10.7.
- [ ] Which command you ran, for example `infer -- make`. 
- [ ] I am trying to install Infer with Docker as per below commands 
   https://fbinfer.com/docs/getting-started/
Docker Commands:
-  wget -O Dockerfile https://raw.githubusercontent.com/facebook/infer/master/docker/0.14.0/Dockerfile
wget -O run.sh https://raw.githubusercontent.com/facebook/infer/master/docker/0.14.0/run.sh
sh run.sh

Due to SSL certificate issues, I have commented curl command inside the Dockerfile and manually downloaded infer-linux64-v1.1.0.tar.gz file, extracted and placed it in the /opt folder of container.
I have added RUN command for each instruction and once everything is success i will Remove it . and Docker file is 

FROM debian:stretch-slim

LABEL maintainer "Infer team"

# mkdir the man/man1 directory due to Debian bug #863199
RUN apt-get update && \
    mkdir -p /usr/share/man/man1
RUN apt-get install autoconf -y &&  apt-get install automake -y && apt-get install cmake -y #--yes --no-install-recommends \
#      autoconf \
#      automake \
#      cmake \
RUN apt-get install curl -y
RUN apt-get install git -y && apt-get install libc6-dev -y
#      git \
#      libc6-dev \
RUN apt-get install libsqlite3-dev -y && apt-get install opam -y && apt-get install openjdk-8-jdk-headless -y
#      opam \
#      openjdk-8-jdk-headless \
RUN apt-get install pkg-config -y && apt-get install python2.7 -y && apt-get install zlib1g-dev -y
#      python2.7 \
#      zlib1g-dev && \
RUN rm -rf /var/lib/apt/lists/*
WORKDIR /opt
COPY . /opt
RUN sh install.sh
#RUN INFER_VERSION=v1.1.0; \
RUN rm -f /infer
RUN ln -s ${PWD}/infer-linux64-v1.1.0 /infer

#compile the infer
RUN OCAML_VERSION=4.06.1+flambda
RUN cd infer && sh build-infer.sh --opam-switch 4.06.1+flambda

Here Symbolink file /infer  has created  for infer-linux-v1-1.1.0 and in next going inside Symbolinkfile /infer and executing build-infer.sh shell script which is NOT present.How to Bring the build-infer.sh script?
Does i missed anything here?
my directory structure:

 ls -ltr
total 36
drwxr-xr-x  5 xxxxx  xxxxx    41 Jun 25 04:06 infer-linux64-v1.1.0
-rwxrwxr-x  1 xxxxx  xxxxx  22845 Jun 25 06:17 install.sh
-rwxrwxr-x  1 xxxxx  xxxxx   1300 Jun 25 06:18 run.sh
-rw-rw-r--  1 xxxxx  xxxxx  1062 Jun 25 06:59 Dockerfile

Thanks
Venkat

- [ ] The full output in a paste, for instance a [gist](https://gist.github.com/).
- [ ] If possible, a minimal example to reproduce your problem (for instance, some code where
    infer reports incorrectly, together with the way you run infer to reproduce the incorrect
    report).

**Comment by jvillard** [comment] 2021-08-06 10:06
Seems like a duplicate of #1460

**Closed by jvillard** 2021-08-06 10:06 UTC
