### ISSUE TITLE
can not build success

### ISSUE THREAD

**Issue by guafei** [facebook/infer#112] opened 2015-06-27 08:34 UTC
Hello,

My project uses cocopods to manage the third libraries, but I enter the folder of project , run the command "infer -- xcodebuild -target xxx -configuration Debug -sdk iphonesimulator"  ,but it builds failed, message is "ld: library not found for -lPods-xxx-AFNetworking
clang++: error: linker command failed with exit code 1 (use -v to see invocation)"
while project can build success by xcode. Which reason may cause this problem, thanks.

**Comment by dulmarod** [comment] 2015-06-29 11:05
Are you using the latest release of Infer? If not, could you try using that latest release and check if you still have the problem?

**Comment by guafei** [comment] 2015-07-02 03:06
Hello @dulmarod,

I upgrade infer version to v0.2.0, when I input command "make -C infer" ,it comes out error message            "File "_none_", line 1:
 Error: Files java/jAnnotation.cmx
 and /Users/guafei/.opam/4.01.0/lib/javalib/javalib.cmxa
 make inconsistent assumptions over implementation Javalib_pack"

Could you kindly help me to solve it, thanks a lot.

**Comment by jeremydubreil** [comment] 2015-07-02 03:13
@guafei: do you still get the same issue if you try with `make -C infer clean && make -C infer` ?

**Comment by guafei** [comment] 2015-07-02 05:33
Hi @jeremydubreil 

You suggestion is great, but I meet an other problem that analyze my project,it builds failed with infer ,while xcode can build success, the error message is 
"The following build commands failed:
	CompileC build/TargetName.build/Debug-iphonesimulator/TargetName-WithoutWatch.build/Objects-normal/i386/SearchWordsCell.o TargetName/Classes/Modules/SearchWordsCell.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC build/TargetName.build/Debug-iphonesimulator/TargetName-WithoutWatch.build/Objects-normal/i386/FeedItemCommentCell.o TargetName/Classes/Modules/FeedItemCommentCell.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC build/TargetName.build/Debug-iphonesimulator/TargetName-WithoutWatch.build/Objects-normal/i386/CommentListViewController.o TargetName/Classes/Modules/CommentListViewController.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(3 failures)
None"

I have no idea about the message, Could you help me to solve it, thanks a lot.

**Comment by martinoluca** [comment] 2015-07-08 10:39
Hello @guafei,
I suspect the problem is related with the fact that in the presence of CocoaPods, you should use the xcworkspace and not the xcodeproj; please try running a command like this (customize according to your project):
```
infer -- xcodebuild -workspace HelloWorld.xcworkspace -scheme HelloWorld
```

you can find the right scheme running:
```
xcodebuild -list
```

**Comment by guafei** [comment] 2015-07-16 09:05
@martinoluca thanks，you give me a trail to further study xcodebulid. I have a question that how can I user infer avoid to compile my c++ code in my project, I meet the problem when I build my project that " CompileC /xxx/CADebugMacros.cpp normal armv7 c++ com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)". 
assign to @dulmarod and @jeremydubreil, hope to  get feedback, thanks.

**Comment by jvillard** [comment] 2015-08-26 11:41
@guafei the way Infer works is by following what the build system of your project does, so to prevent Infer from analysing c++ files, you have to modify your build system to not compile them.

Or you can try this untested trick:
```
CXX=$(which clang++) infer -- xcodebuild <your options here>
```

This will hardcode the c++ compiler to be, eg, /usr/bin/clang++ instead of just clang++. This will prevent Infer from replacing clang++ with its own clang and make this step essentially invisible to Infer.

**Comment by guafei** [comment] 2015-08-31 02:07
Hi @jvillard 
     I have fixed this issue through changing my cpp code, not to prevent Infer from analysing c++ files, I meet the problem which is caused by macro. Thanks for your reply, your suggestion may help others.

**Comment by jvillard** [comment] 2015-09-01 13:56
Glad to hear it. I'm closing this issue then.

**Closed by jvillard** 2015-09-01 13:56 UTC
