### ISSUE TITLE
Binaries for OSX and Linux

### ISSUE THREAD

**Issue by rahulparsani** [facebook/infer#155] opened 2015-07-22 09:51 UTC
Initially when 0.10 was released, we could install infer using precompiled binaries for either Mac OSX or Linux. This was awesome for cloud hosted CI tools like travis. It seems these have since disappeared even though they're mentioned in the [installation instructions](https://github.com/facebook/infer/blob/master/INSTALL.md)

>We provide pre-built Infer binaries for Linux and MacOS. If you just wish to use Infer, and are not interested in making contributions to it, then these binaries are all you need. Otherwise, if you wish to compile Infer, here are also instructions to do so, depending on your operating system.

I would really appreciate if these were brought back. Thanks!

**Comment by jvillard** [comment] 2015-07-22 13:21
Closing this as duplicate of #122 .

**Closed by jvillard** 2015-07-22 13:21 UTC
