### ISSUE TITLE
infer installation failed with configure: error: found version 4.04.0.

### ISSUE THREAD

**Issue by Josehc2004** [facebook/infer#800] opened 2017-11-09 10:51 UTC
OS version Ubuntu 17.10
trying to install infer 0.13.0  
The OCaml toplevel, version 4.05.0
Infer failed with ./configure make
Error:
checking if OCaml version is >= 4.05.0... configure: error: found version 4.04.0.

  Please upgrade to OCaml >= 4.05.0. If you are using opam, you can run

    opam switch 4.05.0
    eval $(opam config env)

**Comment by jvillard** [comment] 2017-11-09 15:13
Have you tried running the suggested commands? `opam switch 4.05.0 && eval $(opam config env) && ./configure && make`.

Alternatively, `./build-infer.sh` will install the right version of OCaml for you.

**Comment by Josehc2004** [comment] 2017-11-10 06:28
After trying the above command received the following error:

  9%] Linking CXX static library ../../libLLVMDebugInfoPDB.a
make[3]: Leaving directory '/tmp/clang-setup.HBmxvJ/build'
[  9%] Built target LLVMDebugInfoPDB
make[2]: Leaving directory '/tmp/clang-setup.HBmxvJ/build'
Makefile:151: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/tmp/clang-setup.HBmxvJ/build'
Makefile:213: recipe for target 'clang_setup' failed
make: *** [clang_setup] Error 2

Already tried ./build-infer.sh got "Unix.Unix_error "Illegal seek" sysconf ""

Uncaught exception:

(Unix.Unix_error "Illegal seek" sysconf "")

Raised by primitive operation at file "src/core_unix.ml", line 348, characters 14-29
Makefile:189: recipe for target '/home/test/infer/infer/man/man1/infer-analyze.1' failed
make: *** [/home/test/infer/infer/man/man1/infer-analyze.1] Error 2
make: *** Waiting for unfinished jobs....

Please help me to install infer on Ubuntu 17.10

**Comment by jvillard** [comment] 2017-11-10 10:50
This looks like a duplicate of #776. Let me answer you there and close this issue.

**Closed by jvillard** 2017-11-10 10:50 UTC
