### ISSUE TITLE
PARAMETER_NOT_NULL_CHECKED not detected when a block is called inside another block

### ISSUE THREAD

**Issue by tettoffensive** [facebook/infer#148] opened 2015-07-16 19:21 UTC
`warning: PARAMETER_NOT_NULL_CHECKED
  Parameter block is not checked for null, there could be a null pointer dereference: pointer block could be null and is dereferenced at line 116, column 9`

I get these whenever I call a `block();` for example without checking `if (block)`. However, I don't get these warnings if that call is inside another block like a `dispatch_async(dispatch_get_main_queue(), ^{ block(); }`

**Comment by jeremydubreil** [comment] 2015-07-16 23:07
Hi @tettoffensive. I don't understand the issue. Is there a way we can reproduce this on a small example ?

**Comment by ddino** [comment] 2015-07-17 12:31
hi tettoffensive,
yeah, nested blocks are not detected so far. This needs to be fixed. We'll look at this issue. 
Thanks for reporting it.

**Comment by jvillard** [comment] 2016-04-20 19:41
Hi @tettoffensive, we have implemented support for nested blocks since you created this issue. I'm closing this issue because we think this has been addressed. Please feel free to reopen if you think there's still an issue in the current version of infer.

**Closed by jvillard** 2016-04-20 19:41 UTC
Labels: low-pri, objective-c
