### ISSUE TITLE
Error: Unbound module Ag_util in yojson_utils.mli

### ISSUE THREAD

**Issue by farao** [facebook/infer#972] opened 2018-07-26 15:35 UTC
Hi,

after going through many steps/changes to be able to compile infer in the clang version (using opam 2 and Fedora Linux 28 - not a good combination so far ;-)), I now got so far that it installs all the opam dependencies and successfully compiled clang, but now I'm getting this error:

    [*ERROR**][9539] ocamlfind ocamlopt -package unix,atdgen,camlzip -I build -safe-string -o build/clang_ast_t.cmi -c build/clang_ast_t.mli
    [*ERROR**][9539] ocamlfind ocamlopt -package unix,atdgen,camlzip -I build -safe-string -o build/yojson_utils.cmi -c yojson_utils.mli
    [*ERROR**][9539] make[1]: 'build/clang_ast_proj.ml' is up to date.
    [*ERROR**][9539] make[1]: 'build/clang_ast_proj.mli' is up to date.
    [*ERROR**][9539] make[1]: Leaving directory '/home/marius/code/infer/facebook-clang-plugins/clang-ocaml'
    [*ERROR**][9539] *** stderr:
    [*ERROR**][9539] File "yojson_utils.mli", line 11, characters 29-48:
    [*ERROR**][9539] Error: Unbound module Ag_util

What went wrong? I checked the module and it's in adtgen but atdgen was/is installed in opam (atdgen version: 2.0.0).

Thanks,
Marius

**Comment by jvillard** [comment] 2018-08-02 12:45
I'm puzzled too! Maybe something weird that happens only in opam2? We haven't migrated to opam 2 so far so that would be my first guess. Does this happen when you do `./build-infer.sh` or running `make` yourself? Do you have "ag_util.cmx" in your ".opam/<switch>/lib/atdgen" folder?

**Comment by ygrek** [comment] 2018-08-04 17:59
Ag_util is module from atdgen < 2, so looks like some generated code was not updated in code (and if generated code is committed to repo need a constrain on atdgen)

**Comment by jvillard** [comment] 2018-08-06 09:38
It's also worth trying to `make clean && ./build-infer.sh` just in case; it's possible that some Makefiles out there are not regenerating outdated artefacts. There's no generated code committed to the repo as far as I know.

**Comment by farao** [comment] 2018-08-07 09:41
Just as a feedback here: clean and recompile didn't work

**Comment by jvillard** [comment] 2018-08-07 10:10
It worked here for someone with the same issue :/ Just to be extra-super-sure, could you try the following from the root of the infer repo?

```
make clean
eval $(opam config env)
opam switch show  # should output "infer-4.06.1+flambda"
./build-infer.sh
```

**Comment by Isweet** [comment] 2018-08-08 18:46
I'm getting a similar error when I do:

```
$ opam pin add infer https://github.com/facebook/infer
$ opam install infer
```

with output:

```
=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
[ERROR] The compilation of infer failed at "make -j4".

...

# [*ERROR**][87955] File "checkers/BoundedCallTree.ml", line 94, characters 4-24:
# [*ERROR**][87955] Error: Unbound module Ag_util
```

**Comment by Isweet** [comment] 2018-08-08 18:48
Per @ygrek's comment, I believe the issue is that my version of `atdgen` is >= 2.

```
$ opam info atdgen
package: atdgen
             version: 2.0.0
```

**Comment by Isweet** [comment] 2018-08-08 18:53
Well, I tried downgrading:

```
$ opam install atdgen.1.13.0
```

but I'm still getting the error:

```
$ opam info atdgen
             package: atdgen
             version: 1.13.0
$ opam install infer
=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
[ERROR] The compilation of infer failed at "make -j4".

...

# [*ERROR**][87955] File "checkers/BoundedCallTree.ml", line 94, characters 4-24:
# [*ERROR**][87955] Error: Unbound module Ag_util
```

**Comment by Isweet** [comment] 2018-08-08 19:11
Looks like `atdgen.1.12.0` works.

**Closed** 2018-08-09 14:34 UTC
