### ISSUE TITLE
False positive NULL_DEREFERENCE for Airlift ConfigurationMetadata

### ISSUE THREAD

**Issue by electrum** [facebook/infer#250] opened 2016-01-28 23:07 UTC
https://github.com/airlift/airlift
```
configuration/src/main/java/io/airlift/configuration/ConfigurationMetadata.java:49: error: NULL_DEREFERENCE
  object returned by metadata.getProblems() could be null and is dereferenced at line 49
  47.       {
  48.           ConfigurationMetadata<T> metadata = getConfigurationMetadata(configClass, monitor);
  49. >         metadata.getProblems().throwIfHasErrors();
  50.           return metadata;
  51.       }
```
`getProblems()` returns a final field which is always initialized as non-null in the constructor.

**Comment by sblackshear** [comment] 2016-02-01 18:41
Duplicate of #249.

**Closed by sblackshear** 2016-02-01 18:41 UTC
