### ISSUE TITLE
run inferTraceBugs  error   and get error after analysis done

### ISSUE THREAD

**Issue by jimmyleaf** [facebook/infer#175] opened 2015-09-14 03:34 UTC
use infer analyize ios project by command:
infer -- xcodebuild clean build -workspace  xxx.xcworkspace -scheme xxx -configuration Debug -sdk iphonesimulator

after build succeeded , I get this error :

** BUILD SUCCEEDED **

Starting analysis (Infer version git-401109b4eb9d54ef8831ee953a3436ec3e2bb72e)

Analysis done

Traceback (most recent call last):
  File "/Users/appdev/infer/infer/bin/infer", line 180, in <module>
    main()
  File "/Users/appdev/infer/infer/bin/infer", line 165, in main
    analysis.analyze_and_report()
  File "/Users/appdev/infer/infer/bin/inferlib.py", line 678, in analyze_and_report
    self.report_errors()
  File "/Users/appdev/infer/infer/bin/inferlib.py", line 638, in report_errors
    print_errors(csv_report, bugs_out)
  File "/Users/appdev/infer/infer/bin/inferlib.py", line 366, in print_errors
    msg,
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 20: ordinal not in range(128)

**Comment by akotulski** [comment] 2015-09-15 14:06
@jimmyleaf I can't reproduce the problem locally (infer doesn't crash for me with unicode characters in error message).

There is one line fix that might fix your problems, could you change inferlib.py file and report back whether it helps? I'll push the patch if it fixes your problem.

The potential fix: add `u` before `'{0}:{1}: {2}: {3}\n  {4}\n'.format(` like so:
http://pastebin.com/EvZ1Hvup
You don't need to recompile anything, just save the file and rerun infer.

**Comment by jimmyleaf** [comment] 2015-09-16 08:23
@akotulski  I add u before '{0}:{1}: {2}: {3}\n {4}\n'.format(  at infer/bin/inferlib.py  line 361 

save the file and I rerun infer command
```
infer -- xcodebuild clean build -workspace xxx.xcworkspace -scheme xxx -configuration Debug -sdk iphonesimulator 
```
at terminal，and I got same error   at last  

```
Traceback (most recent call last):
File "/Users/appdev/infer/infer/bin/infer", line 180, in 
main()
File "/Users/appdev/infer/infer/bin/infer", line 165, in main
analysis.analyze_and_report()
File "/Users/appdev/infer/infer/bin/inferlib.py", line 678, in analyze_and_report
self.report_errors()
File "/Users/appdev/infer/infer/bin/inferlib.py", line 638, in report_errors
print_errors(csv_report, bugs_out)
File "/Users/appdev/infer/infer/bin/inferlib.py", line 366, in print_errors
msg,
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 20: ordinal not in range(128)
```

and  I  run  inferTraceBugs command  at Project path

**Comment by jvillard** [comment] 2015-10-27 15:36
@jimmyleaf can you try running infer with `LANG=C` to see if the error persists?

```sh
LANG=C; infer -- xcodebuild clean build -workspace xxx.xcworkspace -scheme xxx -configuration Debug -sdk iphonesimulator
```

**Comment by jimmyleaf** [comment] 2015-11-02 08:08
@jvillard   I just try  running infer with LANG=C and get the error
```
LANG=C; infer -- xcodebuild clean build -workspace xxx.xcworkspace -scheme xxx -configuration Debug -sdk iphonesimulator
``` 

get same error at lase
```
Traceback (most recent call last):
  File "/Users/appdev/infer/infer/bin/infer", line 180, in <module>
    main()
  File "/Users/appdev/infer/infer/bin/infer", line 165, in main
    analysis.analyze_and_report()
  File "/Users/appdev/infer/infer/bin/inferlib.py", line 678, in analyze_and_report
    self.report_errors()
  File "/Users/appdev/infer/infer/bin/inferlib.py", line 638, in report_errors
    print_errors(csv_report, bugs_out)
  File "/Users/appdev/infer/infer/bin/inferlib.py", line 366, in print_errors
    msg,
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 20: ordinal not in range(128)
```

**Comment by jvillard** [comment] 2015-11-02 21:17
@jimmyleaf is infer-out/toplevel.log created and if so can you copy its contents?

Is there any non-ascii character in the path of the project that you are running infer on? I'm wondering if this is linked to #76.

**Comment by jimmyleaf** [comment] 2015-11-04 02:19
@jvillard   infer-out/toplevel.log created 
```
[INFO] Running command /Users/appdev/infer/infer/bin/infer -- /Users/appdev/Desktop/Xcode.app/Contents/Developer/usr/bin/xcodebuild clean build -workspace PALifeApp.xcworkspace -scheme PALifeApp -configuration Debug -sdk iphonesimulator
[INFO] Path to infer script /Users/appdev/infer/infer/bin/infer (/Users/appdev/infer/infer/bin/infer)
[INFO] Infer version git-401109b4eb9d54ef8831ee953a3436ec3e2bb72e
Copyright 2009 - present Facebook. All Rights Reserved.


[INFO] Platform: Darwin-14.5.0-x86_64-i386-64bit
[INFO] PATH=/Users/appdev/.opam/4.01.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin::/Users/appdev/android/gradle-2.4/bin::/Users/appdev/android/sdk/build-tools/22.0.1:/Users/appdev/android/sdk/tools:/Users/appdev/android/sdk/platform-tools::/Users/appdev/android/android-ndk-r10/:/Users/appdev/infer/infer/bin/
[INFO] SHELL=/bin/bash
[INFO] PWD=/Users/appdev/.jenkins/jobs/PALife_ios_infer/workspace/PALifeApp
[INFO] Xcode version:
Xcode 7.0.1
Build version 7A1001

[INFO] clang version:
Apple LLVM version 7.0.0 (clang-700.0.72)
Target: x86_64-apple-darwin14.5.0
Thread model: posix

[INFO] Capture phase was successful
[INFO] Starting analysis
```
And i can confirm that there is no non-ascii character in the path of the project

**Comment by jvillard** [comment] 2015-11-11 11:24
I can reproduce the error if I write some code with non-ascii chars in them. Let's assume that's what you're seeing here. I'm working on a fix.

```c
void test() {
  int *α = 0;
  *α = 0;
}
```

**Comment by jvillard** [comment] 2015-11-13 17:02
@jimmyleaf I forgot to update this issue to let you know that your issue may now be fixed in the current master. Let me know if that works for you.

**Comment by jvillard** [comment] 2015-11-19 15:10
closing optimistically.

Note that infer still has a problem with unicode in paths, but that's harder to fix as it's caused by the fact that, amongst other things, python2's Popen doesn't deal well with unicode.

**Closed by jvillard** 2015-11-19 15:10 UTC
