### ISSUE TITLE
Failed to build iOS project,how to fix

### ISSUE THREAD

**Issue by yanqi8573** [facebook/infer#335] opened 2016-04-13 06:43 UTC
I use :
infer --incremental  -- xcodebuild -workspace xxx.xcworkspace -scheme xxx -sdk iphonesimulator -configuration Debug -destination 'platform=iOS Simulator,OS=9.2,name=iPhone 6s' CLANG_ENABLE_MODULES=NO clean build

The following build commands failed:
	CompileC /Users/jianzhang/Library/Developer/Xcode/DerivedData/xxxxxxxx-aiaocxwzriymuzayasydwppoqjls/Build/Intermediates/Pods.build/Debug-iphonesimulator/MQTTKit.build/Objects-normal/x86_64/logging_mosq.o MQTTKit/libmosquitto/logging_mosq.c normal x86_64 c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Traceback (most recent call last):
  File "/usr/local/bin/infer", line 178, in <module>
    main()
  File "/usr/local/bin/infer", line 142, in main
    capture_exitcode = imported_module.gen_instance(args, cmd).capture()
  File "/usr/local/Cellar/infer/0.8.0/libexec/infer/lib/python/inferlib/capture/xcodebuild.py", line 78, in capture
    utils.stdout(exc.output)
  File "/usr/local/Cellar/infer/0.8.0/libexec/infer/lib/python/inferlib/utils.py", line 298, in stdout
    print(encode(s, errors=errors))
  File "/usr/local/Cellar/infer/0.8.0/libexec/infer/lib/python/inferlib/utils.py", line 294, in encode
    return u.encode(encoding=config.LOCALE, errors=errors)
AttributeError: 'NoneType' object has no attribute 'encode'

**Comment by ataourirt** [comment] 2016-04-15 12:22
Hi,

I have the same problem.

Have you a solution ?

Thank's

**Comment by jvillard** [comment] 2016-04-15 12:30
Hi @yanqi8573, @ataourirt,

Can you paste the full output of infer to gist.github or similar?

Does the error also occur without infer? Please run `xcodebuild -workspace xxx.xcworkspace -scheme xxx -sdk iphonesimulator -configuration Debug -destination 'platform=iOS Simulator,OS=9.2,name=iPhone 6s' CLANG_ENABLE_MODULES=NO clean build` and let me know, or post the full output to gist.github or similar.

Finally, it would be useful to know if the issue is still present in the latest git version of Infer. Can you please try? Please follow the instructions [here](https://github.com/facebook/infer/blob/master/INSTALL.md) to build from source. Beware that it will build clang, which takes a while.

**Comment by VincentSit** [comment] 2016-04-18 10:17
I have two projects have the same error, same traceback like @yanqi8573 .

The error only occur with infer.   

gist: https://gist.github.com/VincentSit/cb18ce4dc73af64ae98f72db3cfa1f87

**Comment by VincentSit** [comment] 2016-04-18 10:31
Also failed with `CLANG_ENABLE_MODULES=NO clean`.

**Comment by ataourirt** [comment] 2016-04-18 12:17
hi @jvillard 

I used your command line and the build doesn't work. 

The build fail because of this argument :  ```CLANG_ENABLE_MODULES=NO```
Full output : [gist](https://gist.github.com/ataourirt/607ba593963c30794885ff7355a86d99)

Same error with the latest version of Infer (v0.8.0-b7ab176).

**Comment by jvillard** [comment] 2016-04-18 12:24
Thanks for the extra info @VincentSit and @ataourirt 

@ataourirt can you try running the latest version of Infer without the `CLANG_ENABLE_MODULES=NO` flag? I wonder if the newer version of clang we use supports modules now, that would solve the real issue.

**Comment by ataourirt** [comment] 2016-04-18 12:43
Unfortunately, the error is still present @jvillard .

With the latest version (v0.8.0-b7ab176) and this command line :
```infer -- xcodebuild -workspace PagesJaunes.xcworkspace -scheme PagesJaunes -sdk iphonesimulator -configuration Debug clean build```

I have this : [Gist](https://gist.github.com/ataourirt/fa1ed103b94c35fb85a3fe0b6e01379e)

**Comment by VincentSit** [comment] 2016-04-18 13:21
Hi @jvillard , Thanks for the reply. I am trying to build from source and try again. Will give you feedback later.

**Comment by jvillard** [comment] 2016-04-18 14:04
I think the root cause is this issue in clang, which is still open: https://llvm.org/bugs/show_bug.cgi?id=25341

I can reproduce the error on a dummy example and the error goes away if I add `-fno-modules` to the clang arguments. Unfortunately if your project needs modules to compile then it's not a solution for you. 

Someone reported being able to selectively disable modules here: https://github.com/facebook/infer/issues/232#issuecomment-173378896

If someone knows how to pass this sort of options to xcodebuild from the command line then we can add them to infer.

**Comment by VincentSit** [comment] 2016-04-18 16:22
Hi @jvillard . I compiled a few times, but all failed, can you help me to analyze the log?

You can find the log [here](https://gist.github.com/VincentSit/413fd6273728b6a81f55772177229f11).

OS X 10.11.4 (15E65)   
Xcode 7.3 (7D175)

**Comment by jvillard** [comment] 2016-04-18 16:29
@VincentSit the error is at the end of the llvm compilation: `cp: /private/tmp/clang-setup.GnyT8E/tools/clang/runtime/compiler-rt/clang_darwin/10.4/libcompiler_rt.a: No such file or directory`. Not sure what's going on there...

**Comment by VincentSit** [comment] 2016-04-19 02:54
Hi @jvillard , I successfully compiled and install infer on another Mac (commit 82670de0c8930a9ee8d19e154c995d2d609dcf92). But still build failed, when I disable module, remove the [facebook pop](https://github.com/facebook/pop), build succeeded.

Seems if objective-c++ project in Pods, it will cause the build to fail.

Analysis results helps me fix many potential bug, thanks!

**Comment by VincentSit** [comment] 2016-04-19 03:11
BTW, Infer install from brew can also build success.

**Comment by martinoluca** [comment] 2016-04-19 10:50
Hello @ataourirt and @VincentSit,
Could you please try to remove the `CLANG_ENABLE_MODULES=NO` argument and use `CLANG_CXX_LIBRARY=libstdc++` instead?

Thus your `xcodebuild` command will look like this:
`infer -- xcodebuild <args> CLANG_CXX_LIBRARY=libstdc++`

Thanks!

**Comment by VincentSit** [comment] 2016-04-19 11:58
Hi @martinoluca , build failed with `CLANG_CXX_LIBRARY=libstdc++`.

You can find the log [here](https://gist.github.com/VincentSit/d5a70434b15b7db024cf7d2589e27ded).

**Comment by ataourirt** [comment] 2016-04-19 12:13
Hi @martinoluca, same result as @VincentSit

**Comment by akotulski** [comment] 2016-04-19 12:18
This failure is infer's fault. I'll need to investigate why it happens, but it shouldn't happen in trunk (as of a8de56e9bfa5fe74943630ec1555d4b88e84f4ff) with default options.

Which version of infer are you using? If it's 0.8.0, could you remove those two lines from infer and see if compilation succeeds (no recompilation of infer is required, just modify files and run xcodebuild again)?
https://github.com/facebook/infer/blob/v0.8.0/infer/lib/clang_wrappers/clang_wrapper#L14-L15

**Comment by jvillard** [comment] 2016-04-19 12:42
@VincentSit can you try `CLANG_CXX_LIBRARY=libstdc++` again using infer master? The version you compiled earlier is fine.

**Comment by ataourirt** [comment] 2016-04-19 12:42
Hi @akotulski, I use the latest git version : v0.8.0-5710a3e

**Comment by jvillard** [comment] 2016-04-19 12:43
@ataourirt interesting, can you please paste the full output?

**Comment by ataourirt** [comment] 2016-04-19 12:51
@jvillard here is the command line : 

```infer -- xcodebuild -workspace PagesJaunes.xcworkspace -scheme PagesJaunes -sdk iphonesimulator -configuration Debug -destination 'platform=iOS Simulator,OS=9.3,name=iPhone 6s' CLANG_CXX_LIBRARY=libstdc++ clean build```

Output : [Gist](https://gist.githubusercontent.com/ataourirt/64b268048e9cef31f99834ab7ffaae2b/raw/fe2c6312e80fe302fcf2c4410858d516a8fe9476/xcodebuild.log)

**Comment by jvillard** [comment] 2016-04-19 13:09
Thanks @ataourirt . Could you try [this patch](https://gist.github.com/jvillard/202394e8afeaa200b25fa612edfa4ffb)? Apply it from the root of the infer repo with `patch -p1 < xcodebuild_use_apple_libc++_headers.patch`, then try your command again without `CLANG_CXX_LIBRARY=libstdc++`.

**Comment by ataourirt** [comment] 2016-04-19 13:32
Patch does not change anything unfortunately @jvillard.

The output is the same with and without the patch.

**Comment by VincentSit** [comment] 2016-04-19 13:38
Hi @jvillard .

I have been off work. My Mac can not compile infer, I will try again tomorrow when I  go to company.

**Comment by jvillard** [comment] 2016-04-19 13:48
@ataourirt did you remove `CLANG_CXX_LIBRARY=libstdc++` from the command? That is, you should run:

```
infer -- xcodebuild -workspace PagesJaunes.xcworkspace -scheme PagesJaunes -sdk iphonesimulator -configuration Debug -destination 'platform=iOS Simulator,OS=9.3,name=iPhone 6s' clean build
```

**Comment by ataourirt** [comment] 2016-04-19 14:42
@jvillard, here is the [output](https://gist.githubusercontent.com/ataourirt/170c448ea004e667c5b0bd6f19d3142b/raw/d58f22380419cf90a181a3fb8ee11bb7bb0d0dd3/xcodebuild%2520with%2520Infer%2520version%2520v0.8.0-5710a3e)

**Comment by VincentSit** [comment] 2016-04-20 02:19
@jvillard Unfortunately, It can not be build.

[Log](https://gist.github.com/VincentSit/f21d80e4db1625bb1d34ee81ac22796d)

If I remove Objective-C++ project from Pods (In my case, there only have one, Facebook pop), it successfully build.

**Comment by akotulski** [comment] 2016-04-20 10:40
I just committed 1be7827981048291331343be06b0e84be45592c3 which should fix issues with compiling CocoaPods. You should run infer -- <build_command> without any special flags and it should succeed.

Could you try it out and let us know if it helps?

**Comment by VincentSit** [comment] 2016-04-20 11:15
Hi @akotulski , I have sync my local repository with the remote, and recompile infer, now I can build successfully. Thank you!

**Comment by jvillard** [comment] 2016-04-20 11:31
Thanks for helping us fix this issue @ataourirt et @VincentSit

**Closed by jvillard** 2016-04-20 11:31 UTC
