### ISSUE TITLE
Obj-C False positive: malloc used to pass buffer to NSData using freeWhenDone

### ISSUE THREAD

**Issue by loufranco** [facebook/infer#95] opened 2015-06-23 18:20 UTC
This code snippet

```objectivec
uint8_t *buffer = malloc(size * sizeof(uint8_t));
/// fill buffer code here
return [NSData dataWithBytesNoCopy:buffer length:size freeWhenDone:YES];
```

is flagged as 

```
error: MEMORY_LEAK
   memory dynamically allocated to buffer by call to malloc() at line ... is not reachable after line ...
```

**Comment by dulmarod** [comment] 2015-06-23 19:25
Duplicate of https://github.com/facebook/infer/issues/52.

**Closed by dulmarod** 2015-06-23 19:25 UTC
