### ISSUE TITLE
Out of memory when the `bufferoverrun` checker enabled

### ISSUE THREAD

**Issue by zyh1121** [facebook/infer#1246] opened 2020-04-01 02:04 UTC
Please make sure your issue is not addressed in the [FAQ] :ballot_box_with_check:

Please include the following information:
- [x] The version of infer from `infer --version`.
    ```shell
    Infer version v0.17.0-ce1ba6a
    Copyright 2009 - present Facebook. All Rights Reserved.
    ```
- [x] Your operating system and version, for example "Debian 9", "MacOS High Sierra", whether you are using Docker, etc.
    Both `PowerPC` and `Ubuntu`

- [x] Which command you ran, for example `infer -- make`.
    - `infer run --bufferoverrun --no-linters --no-fragment-retains-view --no-inefficient-keyset-iterator --no-self_in_block --enable-issue-type ARRAY_OUT_OF_BOUNDS_L1 --enable-issue-type ARRAY_OUT_OF_BOUNDS_L2 --enable-issue-type ARRAY_OUT_OF_BOUNDS_L3 --enable-issue-type BUFFER_OVERRUN_L4 --enable-issue-type BUFFER_OVERRUN_L5 --enable-issue-type BUFFER_OVERRUN_U5 --enable-issue-type DANGLING_POINTER_DEREFERENCE --enable-issue-type DIVIDE_BY_ZERO --enable-issue-type INTEGER_OVERFLOW_L5 --enable-issue-type INTEGER_OVERFLOW_U5 --enable-issue-type NULLPTR_DEREFERENCE --enable-issue-type PULSE_MEMORY_LEAK --enable-issue-type UNTRUSTED_BUFFER_ACCESS --enable-issue-type UNTRUSTED_HEAP_ALLOCATION --reactive -j 1 -- make -j 1`
   

- [x] The full output in a paste.
   https://gist.github.com/zyh1121/49dd3d410a187c1beed52693b1d19f10

- [x] If possible, a minimal example to reproduce your problem (for instance, some code where
    infer reports incorrectly, together with the way you run infer to reproduce the incorrect
    report).
    - `git clone https://github.com/FFmpeg/FFmpeg.git`
    - `cd FFmpeg`
    - `git reset --hard 8bdba1092f50d52e0af90f425811302ec91152f8`
    - `./configure --disable-altivec --disable-doc`  
    - `infer run --bufferoverrun --no-linters --no-fragment-retains-view --no-inefficient-keyset-iterator --no-self_in_block --enable-issue-type ARRAY_OUT_OF_BOUNDS_L1 --enable-issue-type ARRAY_OUT_OF_BOUNDS_L2 --enable-issue-type ARRAY_OUT_OF_BOUNDS_L3 --enable-issue-type BUFFER_OVERRUN_L4 --enable-issue-type BUFFER_OVERRUN_L5 --enable-issue-type BUFFER_OVERRUN_U5 --enable-issue-type DANGLING_POINTER_DEREFERENCE --enable-issue-type DIVIDE_BY_ZERO --enable-issue-type INTEGER_OVERFLOW_L5 --enable-issue-type INTEGER_OVERFLOW_U5 --enable-issue-type NULLPTR_DEREFERENCE --enable-issue-type PULSE_MEMORY_LEAK --enable-issue-type UNTRUSTED_BUFFER_ACCESS --enable-issue-type UNTRUSTED_HEAP_ALLOCATION --reactive -j 1 -- make -j 1`

On PowerPC, I was able to take the following screenshot before OOM. 
![image](https://user-images.githubusercontent.com/12649708/78091620-66cc1f80-739b-11ea-9f1a-736dae426def.png)

**Comment by skcho** [comment] 2020-04-01 10:19
@zyh1121 Thank you for the report.

First I would like to explain "checkers and issue types". While you added some issues with `--enable-issue-type`, which would not make corresponding checkers run. You may want to run the next four checkers to get all the issues you wrote.

`--biabduction` (enabled by default)
ARRAY_OUT_OF_BOUNDS_L1
ARRAY_OUT_OF_BOUNDS_L2
ARRAY_OUT_OF_BOUNDS_L3
DANGLING_POINTER_DEREFERENCE
DIVIDE_BY_ZERO

`--bufferoverrun` (disabled by default)
BUFFER_OVERRUN_L4
BUFFER_OVERRUN_L5
BUFFER_OVERRUN_U5
INTEGER_OVERFLOW_L5
INTEGER_OVERFLOW_U5

`--pulse` (disabled by default)
NULLPTR_DEREFERENCE 
PULSE_MEMORY_LEAK

`--quandary` (disabled by default)
UNTRUSTED_BUFFER_ACCESS
UNTRUSTED_HEAP_ALLOCATION

On the other hand, if we want to know which checker is the root cause of the OOM, it would be better for us to run the checkers one by one. For example,

`infer run --biabduction-only -- make`
`infer run --bufferoverrun-only -- make`
`infer run --pulse-only -- make`
`infer run --quandary-only -- make`

If you want experimental or blacklisted issue types in the results, e.g. INTEGER_OVERFLOW_L5, add `--no-filtering` option.

**Comment by zyh1121** [comment] 2020-04-01 12:08
@skcho Thanks a lot for the explanation of the issue types! I guess they are used to filter out issues that are already generated in the analysis phase so I didn't expect enabling more issue types would significantly increase memory usages. 

Oh, sorry. I forgot to mention that we also tried the same parameters but just without bufferoverrun. We didn't saw extremely high memory usages. But --bufferoverrun-only is a good idea. We will try and report later. 

Thanks again!

**Comment by skcho** [comment] 2020-04-01 14:36
> we also tried the same parameters but just without bufferoverrun. We didn't saw extremely high memory usages.

OK, then the bufferoverrun checker should be the problem. I will have a look.

**Comment by zyh1121** [comment] 2020-04-01 18:56
@skcho thanks! I also tried `infer run --bufferoverrun-only -j 1 -- make -j 1` as follows

```shell
git clone https://github.com/FFmpeg/FFmpeg.git
cd FFmpeg
git reset --hard 8bdba1092f50d52e0af90f425811302ec91152f8
./configure --disable-altivec --disable-doc
infer run --bufferoverrun-only -j 1 -- make -j 1
```


It looks like Infer gets stuck with `libavfilter/avfiltergraph.c: query_formats` according to the msg in console. The clock stays at `18.753s` while the memory usage grows.

![image](https://user-images.githubusercontent.com/12649708/78169620-adfbf400-741f-11ea-9576-c089898d3ee5.png)

![image](https://user-images.githubusercontent.com/12649708/78169679-c66c0e80-741f-11ea-8fbd-43b2cbddf2e6.png)

![image](https://user-images.githubusercontent.com/12649708/78171930-392ab900-7423-11ea-91c2-2d7a939fc431.png)

![image](https://user-images.githubusercontent.com/12649708/78174960-1949c400-7428-11ea-9b20-7cf1bbe5e595.png)

![image](https://user-images.githubusercontent.com/12649708/78175503-fb309380-7428-11ea-967c-a849f589bdd4.png)

**Comment by skcho** [comment] 2020-04-06 15:55
@zyh1121  Hello. The root cause of the issue was that the bufferoverrun checker created exponentially many internal values during the analysis in some specific cases.

To mitigate it, I added an option, `--bo-field-depth-limit` (cfe4c62e472a12b89e075ae375538c6b4f8bc202), that limits the number of internal values. Instead, it loses some analysis precision. I tested it with the example above:

```
$ infer run --bufferoverrun-only -j 1 --bo-field-depth-limit 3 -- make -j 1
```

should terminate in a reasonable amount of time, of course on the latest master branch.

Thank you for reporting this again. Feel free to reopen if you encounter a similar issue.

**Comment by zyh1121** [comment] 2020-04-09 20:03
@skcho Hey, thank you again for the fix. It works very well on a few hundred commits of ffmpeg. The max memory usage I observed was like 1.5g. 

There could be a minor issue. Infer gets stuck on only one commit. Like what we saw previously, there is no update in the console as shown in following screenshot. The timer looks stopped.

![image](https://user-images.githubusercontent.com/12649708/78935299-7b36a900-7a7a-11ea-9151-987b59ea4fb4.png)

The memory usage went up slowly but stayed almost the same when it reached to 300+g 

![image](https://user-images.githubusercontent.com/12649708/78935528-ee401f80-7a7a-11ea-99bd-10362f5dd17c.png)

![image](https://user-images.githubusercontent.com/12649708/78935611-0fa10b80-7a7b-11ea-9372-6e09f61aaaa0.png)

![image](https://user-images.githubusercontent.com/12649708/78935649-25163580-7a7b-11ea-9652-48e8fb9f8355.png)

```shell
$infer --version
Infer version v0.17.0-f0afa18
Copyright 2009 - present Facebook. All Rights Reserved
```

The following are the steps:

- `$ git checkout 159aa1275e5d9c94edc313a51d65220e887d790b`
- `$ ./configure --disable-altivec --disable-doc`
- `$ infer run --bufferoverrun-only -j 1 --bo-field-depth-limit 3 -- make -j 1`

**Comment by skcho** [comment] 2020-04-14 10:04
@zyh1121 Thank you for the report!

I was able to reproduce the issue. The root cause of the issue, explosion of abstract locations, is the same to before, however it is not suppressed well by the field depth limitation this time. I will try to fix this sooner or later.

**Comment by skcho** [comment] 2020-04-16 11:31
@zyh1121 Hello. I committed a fix 30ca51366d4b49efbd7bed2bad7948dde363b943. The issue above disappeared in my machine. Could you try again with the latest master?

**Comment by skcho** [comment] 2020-04-16 12:19
Feel free to reopen if there is another issue. Thank you so much!

**Closed by skcho** 2020-04-16 12:19 UTC
Labels: bug

**Comment by zyh1121** [comment] 2020-04-16 15:20
@skcho Thank you so much for the quick response!! I will try and report back. However, I observed an odd build issue. 

* Seg fault in a fresh build of 30ca513 (removed all opam packages and re-inited before build). However, `./build-infer.sh all` works fine on the same machine  after I did a git pull from a succesful build of f0afa18 to 54c4715adc37fb821b6c160bb00a03b00ca76ccc. Should I open an issue to document this? Thanks again!!

```shell
$./build-infer.sh all

...

config.status: creating Makefile.autoconf
[10:39:36][ 99567] Building clang plugin...
[      0s][ 99567] SUCCESS Building clang plugin
[10:39:36][ 99579] Building clang plugin OCaml interface...
[      1s][ 99579] SUCCESS Building clang plugin OCaml interface
[10:39:37][ 99704] Generating source dependencies...
[      2s][ 99704] SUCCESS Generating source dependencies
[10:39:39][100082] Building native(opt) Infer...
[*ERROR**][100082] *** ERROR 'Building native(opt) Infer'
[*ERROR**][100082] *** command: ' make INTERACTIVE=1 -C /gpfs/r92gpfs02/zhengyu/local_setup/infer/infer/src infer'
[*ERROR**][100082] *** CWD: '/gpfs/automountdir/r92gpfs02/zhengyu/local_setup/infer'
[*ERROR**][100082] *** stdout:
[*ERROR**][100082] make[1]: Entering directory `/gpfs/automountdir/r92gpfs02/zhengyu/local_setup/infer/infer/src'
[*ERROR**][100082] make[1]: Leaving directory `/gpfs/automountdir/r92gpfs02/zhengyu/local_setup/infer/infer/src'
[*ERROR**][100082] *** stderr:
[*ERROR**][100082] make[1]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.
[*ERROR**][100082] Entering directory '/gpfs/automountdir/r92gpfs02/zhengyu/local_setup/infer/infer'
[*ERROR**][100082]     ocamlopt src/atd/.InferGenerated.objs/native/inferGenerated__Clang_ast_j.{cmx,o} (got signal SEGV)
[*ERROR**][100082] (cd _build/default && /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/bin/ocamlopt.opt -g -short-paths -safe-string -principal -strict-formats -strict-sequence -bin-annot -w +3+5+6+8+10+11+12+14+18+19+20+21+23+26+29+27+28+32+33+34+35+37+38+39+50+52+57+60-4-9-40-41-42-45-48 -w -27-32-34-35-39 -g -O3 -I src/atd/.InferGenerated.objs/byte -I src/atd/.InferGenerated.objs/native -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/atdgen -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/atdgen-runtime -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/base -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/base/base_internalhash_types -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/base/caml -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/base/md5 -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/base/shadow_stdlib -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/base_bigstring -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/base_quickcheck -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/bin_prot -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/bin_prot/shape -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/biniou -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/core -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/core/error_checking_mutex -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/core_kernel -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/core_kernel/base_for_tests -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/core_kernel/bounded_int_table -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/core_kernel/flags -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/core_kernel/version_util -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/easy-format -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/fieldslib -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/jane-street-headers -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/ocaml/threads -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/parsexp -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/ppx_assert/runtime-lib -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/ppx_bench/runtime-lib -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/ppx_compare/runtime-lib -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/ppx_enumerate/runtime-lib -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/ppx_expect/collector -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/ppx_expect/common -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/ppx_expect/config -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/ppx_hash/runtime-lib -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/ppx_here/runtime-lib -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/ppx_inline_test/config -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/ppx_inline_test/runtime-lib -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/ppx_module_timer/runtime -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/ppx_sexp_conv/runtime-lib -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/sexplib -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/sexplib/unix -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/sexplib0 -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/spawn -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/splittable_random -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/stdio -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/time_now -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/typerep -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/variantslib -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/yojson -intf-suffix .ml -no-alias-deps -open InferGenerated -o src/atd/.InferGenerated.objs/native/inferGenerated__Clang_ast_j.cmx -c -impl src/atd/clang_ast_j.pp.ml)
[*ERROR**][100082] make[1]: *** [/gpfs/automountdir/r92gpfs02/zhengyu/local_setup/infer/infer/bin/infer.exe] Error 1
make: *** [src_build] Error 2

  compilation failure; you can try running

    make clean
    './build-infer.sh' all


$cd infer/
$cd _build/default && /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/bin/ocamlopt.opt -g -short-paths -safe-string -principal -strict-formats -strict-sequence -bin-annot -w +3+5+6+8+10+11+12+14+18+19+20+21+23+26+29+27+28+32+33+34+35+37+38+39+50+52+57+60-4-9-40-41-42-45-48 -w -27-32-34-35-39 -g -O3 -I src/atd/.InferGenerated.objs/byte -I src/atd/.InferGenerated.objs/native -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/atdgen -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/atdgen-runtime -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/base -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/base/base_internalhash_types -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/base/caml -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/base/md5 -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/base/shadow_stdlib -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/base_bigstring -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/base_quickcheck -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/bin_prot -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/bin_prot/shape -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/biniou -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/core -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/core/error_checking_mutex -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/core_kernel -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/core_kernel/base_for_tests -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/core_kernel/bounded_int_table -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/core_kernel/flags -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/core_kernel/version_util -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/easy-format -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/fieldslib -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/jane-street-headers -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/ocaml/threads -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/parsexp -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/ppx_assert/runtime-lib -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/ppx_bench/runtime-lib -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/ppx_compare/runtime-lib -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/ppx_enumerate/runtime-lib -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/ppx_expect/collector -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/ppx_expect/common -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/ppx_expect/config -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/ppx_hash/runtime-lib -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/ppx_here/runtime-lib -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/ppx_inline_test/config -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/ppx_inline_test/runtime-lib -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/ppx_module_timer/runtime -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/ppx_sexp_conv/runtime-lib -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/sexplib -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/sexplib/unix -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/sexplib0 -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/spawn -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/splittable_random -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/stdio -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/time_now -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/typerep -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/variantslib -I /gpfs/automountdir/r92gpfs02/zhengyu/opam_repo/ocaml-variants.4.08.1+flambda/lib/yojson -intf-suffix .ml -no-alias-deps -open InferGenerated -o src/atd/.InferGenerated.objs/native/inferGenerated__Clang_ast_j.cmx -c -impl src/atd/clang_ast_j.pp.ml
Segmentation fault

$pwd
/gpfs/r92gpfs02/zhengyu/local_setup/infer/infer/_build/default
```

**Comment by skcho** [comment] 2020-04-16 18:44
Hmmm... it is strange.  30ca513 does not seem to related to the compile error. Have you tried `make clean`? Does this happen in both powerpc and ubuntu?

> Should I open an issue to document this?

I think it is better to get more help. :)

**Comment by zyh1121** [comment] 2020-04-16 19:01
I guess it's probably due to some changes f0afa18 and 30ca513. (my f0afa18 was a fresh build and the build process was successful). I will open an issue later. thanks again!

**Comment by vickyw1112** [comment] 2022-03-03 06:07
> internal values

shall I ask what are internal values?
