### ISSUE TITLE
JDK: You are attempting to build with the incorrect version of javac

### ISSUE THREAD

**Issue by vrusnak** [facebook/infer#769] opened 2017-10-13 12:24 UTC
Hi,
I try to build our AOSP Android project after installing all dependencies on Ubuntu 16 and building precompiled Infer from Github (https://github.com/facebook/infer/releases/tag/v0.12.1)

The command I'm using is 'infer run -- make' and I always get this error in the console output:

Checking build tools versions...
*****************************************************
You are attempting to build with the incorrect version
of javac.
Your version is: $INFER_RESULTS_DIR with a path to the results dir not provided..
The required version is: "1.8"
Please follow the machine setup instructions at
https://source.android.com/source/download.html
*****************************************************
My java ENV variables are 
$ echo $JAVA_HOME
/usr/lib/jvm/java-8-openjdk-amd64
$ echo $ANDROID_JAVA_HOME
/usr/lib/jvm/java-8-openjdk-amd64

Does anyone recognize this problem?

**Comment by jvillard** [comment] 2017-10-13 14:18
Thanks for the report. I believe this should be fixed by 9a2746c14311c5b7fad69b67d372a3aa5de347e5. Please let me know if the issue is still there in the latest master.

**Closed** 2017-11-06 16:38 UTC
