### ISSUE TITLE
infer-0.9.4.1.sierra not working for iOS

### ISSUE THREAD

**Issue by evgzor** [facebook/infer#552] opened 2017-01-02 11:35 UTC
[infer_49785_a86434-out.log.zip](https://github.com/facebook/infer/files/680721/infer_49785_a86434-out.log.zip)

Hi,

I have some problem please c below:

evgzor$ infer -- xcodebuild -target CustomDatePicker -configuration Debug -sdk iphonesimulator
0.2.4
2017-01-02 14:08:11.428 xcodebuild[41219:131183] [MT] PluginLoading: Required plug-in compatibility UUID E0A62D1F-3C18-4D74-BFE5-A4167D643966 for plug-in at path '/Library/Application Support/Developer/Shared/Xcode/Plug-ins/VVDocumenter-Xcode.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2017-01-02 14:08:11.428 xcodebuild[41219:131183] [MT] PluginLoading: Required plug-in compatibility UUID E0A62D1F-3C18-4D74-BFE5-A4167D643966 for plug-in at path '/Library/Application Support/Developer/Shared/Xcode/Plug-ins/SCXcodeSwitchExpander.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2017-01-02 14:08:11.429 xcodebuild[41219:131183] [MT] PluginLoading: Required plug-in compatibility UUID E0A62D1F-3C18-4D74-BFE5-A4167D643966 for plug-in at path '/Library/Application Support/Developer/Shared/Xcode/Plug-ins/ObjectGraph.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2017-01-02 14:08:11.429 xcodebuild[41219:131183] [MT] PluginLoading: Required plug-in compatibility UUID E0A62D1F-3C18-4D74-BFE5-A4167D643966 for plug-in at path '/Library/Application Support/Developer/Shared/Xcode/Plug-ins/KSHObjcUML.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2017-01-02 14:08:11.429 xcodebuild[41219:131183] [MT] PluginLoading: Required plug-in compatibility UUID E0A62D1F-3C18-4D74-BFE5-A4167D643966 for plug-in at path '/Library/Application Support/Developer/Shared/Xcode/Plug-ins/FuzzyAutocomplete.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2017-01-02 14:08:11.429 xcodebuild[41219:131183] [MT] PluginLoading: Required plug-in compatibility UUID E0A62D1F-3C18-4D74-BFE5-A4167D643966 for plug-in at path '/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs
▸ Building CustomDatePicker/CustomDatePicker [Debug]
▸ Check Dependencies
▸ Precompiling CustomDatePicker/CustomDatePicker-Prefix.pch
▸ Compiling main.m
▸ Compiling AppDelegate.m
▸ Compiling ViewController.m
▸ Compiling CustomDatePicker.m
▸ Compiling CustomPickerView.m
▸ Linking CustomDatePicker
▸ Copying InfoPlist.strings
▸ Compiling ViewController_iPhone.xib
▸ Compiling ViewController_iPad.xib
▸ Compiling LaunchScreen.storyboard
▸ Processing CustomDatePicker-Info.plist
▸ Touching CustomDatePicker.app
▸ Signing build/Debug-iphonesimulator/CustomDatePicker.app
▸ Build Succeeded
Capturing using xcpretty...
Starting translating 5 files
Uncaught exception:

(Unix.Unix_error "No such file or directory" chdir
"/Users/evgzor/Google\ Drive/Projects/CustomDatePickerView/CustomDatePickerNoArc")

Called from file "base/Process.ml", line 111, characters 2-12
Called from file "backend/infer.ml", line 314, characters 2-30
Uncaught exception:

(Unix.Unix_error "No such file or directory" chdir
"/Users/evgzor/Google\ Drive/Projects/CustomDatePickerView/CustomDatePickerNoArc")

Called from file "base/Process.ml", line 111, characters 2-12
Called from file "backend/infer.ml", line 314, characters 2-30
..Uncaught exception:

(Unix.Unix_error "No such file or directory" chdir
"/Users/evgzor/Google\ Drive/Projects/CustomDatePickerView/CustomDatePickerNoArc")

Called from file "base/Process.ml", line 111, characters 2-12
Called from file "backend/infer.ml", line 314, characters 2-30
Uncaught exception:

(Unix.Unix_error "No such file or directory" chdir
"/Users/evgzor/Google\ Drive/Projects/CustomDatePickerView/CustomDatePickerNoArc")

Called from file "base/Process.ml", line 111, characters 2-12
Called from file "backend/infer.ml", line 314, characters 2-30
..Uncaught exception:

(Unix.Unix_error "No such file or directory" chdir
"/Users/evgzor/Google\ Drive/Projects/CustomDatePickerView/CustomDatePickerNoArc")

Called from file "base/Process.ml", line 111, characters 2-12
Called from file "backend/infer.ml", line 314, characters 2-30
..
Starting analysis...

legend:
"F" analyzing a file
"." analyzing a procedure

Found 0 source files in /Users/evgzor/Google Drive/Projects/CustomDatePickerView/CustomDatePickerNoArc/infer-out

Traceback (most recent call last):
File "/usr/local/Cellar/infer/0.9.4.1/lib/infer/infer/bin/../lib/python/report.py", line 20, in 
from inferlib import config, issues, utils
File "/usr/local/Cellar/infer/0.9.4.1/lib/infer/infer/lib/python/inferlib/config.py", line 19, in 
CODESET = locale.getlocale(locale.LC_CTYPE)[1]
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 562, in getlocale
return _parse_localename(localename)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 475, in _parse_localename
raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8
** Error running the reporting script:
** /usr/local/Cellar/infer/0.9.4.1/lib/infer/infer/bin/../lib/python/report.py --issues-csv /Users/evgzor/Google Drive/Projects/CustomDatePickerView/CustomDatePickerNoArc/infer-out/report.csv --issues-json /Users/evgzor/Google Drive/Projects/CustomDatePickerView/CustomDatePickerNoArc/infer-out/report.json --project-root /Users/evgzor/Google Drive/Projects/CustomDatePickerView/CustomDatePickerNoArc --results-dir /Users/evgzor/Google Drive/Projects/CustomDatePickerView/CustomDatePickerNoArc/infer-out
** See error above

U may try to analyze my project: https://github.com/evgzor/CustomDatePickerView/tree/master/CustomDatePickerNoArc

**Comment by martinoluca** [comment] 2017-01-03 10:14
Hi @evgzor,
have you tried running the xcodebuild command without `infer`, that is:
```
 xcodebuild -target CustomDatePicker -configuration Debug -sdk iphonesimulator
0.2.4
```
and see whether it succeeds or not?

If succeeds, maybe it's the space in the path where the project is located:
```
/Users/evgzor/Google\ Drive/Projects/...
```
Try renaming it to a name without spaces and see if it keeps failing.

Let me know, thanks!

**Comment by evgzor** [comment] 2017-01-03 10:34
Hi,

Another error : 
2017-01-03 13:33:04.092 xcodebuild[39155:465229] [MT] PluginLoading: Required plug-in compatibility UUID E0A62D1F-3C18-4D74-BFE5-A4167D643966 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/VVDocumenter-Xcode.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2017-01-03 13:33:04.092 xcodebuild[39155:465229] [MT] PluginLoading: Required plug-in compatibility UUID E0A62D1F-3C18-4D74-BFE5-A4167D643966 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/SCXcodeSwitchExpander.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2017-01-03 13:33:04.093 xcodebuild[39155:465229] [MT] PluginLoading: Required plug-in compatibility UUID E0A62D1F-3C18-4D74-BFE5-A4167D643966 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/ObjectGraph.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2017-01-03 13:33:04.093 xcodebuild[39155:465229] [MT] PluginLoading: Required plug-in compatibility UUID E0A62D1F-3C18-4D74-BFE5-A4167D643966 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/KSHObjcUML.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2017-01-03 13:33:04.093 xcodebuild[39155:465229] [MT] PluginLoading: Required plug-in compatibility UUID E0A62D1F-3C18-4D74-BFE5-A4167D643966 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/FuzzyAutocomplete.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2017-01-03 13:33:04.094 xcodebuild[39155:465229] [MT] PluginLoading: Required plug-in compatibility UUID E0A62D1F-3C18-4D74-BFE5-A4167D643966 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs
▸ Building CustomDatePicker/CustomDatePicker [Debug]
▸ Check Dependencies
▸ Build Succeeded
Capturing using xcpretty...
Starting translating 0 files 
.
Starting analysis...

legend:
  "F" analyzing a file
  "." analyzing a procedure

Found 0 source files in /Users/evgzor/Dropbox/Projects/CustomDatePickerView/CustomDatePickerNoArc/infer-out

Traceback (most recent call last):
  File "/usr/local/Cellar/infer/0.9.4.1/lib/infer/infer/bin/../lib/python/report.py", line 20, in <module>
    from inferlib import config, issues, utils
  File "/usr/local/Cellar/infer/0.9.4.1/lib/infer/infer/lib/python/inferlib/config.py", line 19, in <module>
    CODESET = locale.getlocale(locale.LC_CTYPE)[1]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 562, in getlocale
    return _parse_localename(localename)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 475, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8
** Error running the reporting script:
**   /usr/local/Cellar/infer/0.9.4.1/lib/infer/infer/bin/../lib/python/report.py --issues-csv /Users/evgzor/Dropbox/Projects/CustomDatePickerView/CustomDatePickerNoArc/infer-out/report.csv --issues-json /Users/evgzor/Dropbox/Projects/CustomDatePickerView/CustomDatePickerNoArc/infer-out/report.json --project-root /Users/evgzor/Dropbox/Projects/CustomDatePickerView/CustomDatePickerNoArc --results-dir /Users/evgzor/Dropbox/Projects/CustomDatePickerView/CustomDatePickerNoArc/infer-out
** See error above

**Comment by jberdine** [comment] 2017-01-03 11:35
UTF-8 is not a valid locale.  This is probably a duplicate of #447 .

**Comment by evgzor** [comment] 2017-01-03 12:20
I did export LC_ALL=en_US.UTF-8
and :
MacBook-Pro:CustomDatePickerNoArc evgzor$ infer -- xcodebuild -target CustomDatePicker -configuration Debug -sdk iphonesimulator
0.2.4
2017-01-03 15:15:54.661 xcodebuild[43952:479696] [MT] PluginLoading: Required plug-in compatibility UUID E0A62D1F-3C18-4D74-BFE5-A4167D643966 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/VVDocumenter-Xcode.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2017-01-03 15:15:54.661 xcodebuild[43952:479696] [MT] PluginLoading: Required plug-in compatibility UUID E0A62D1F-3C18-4D74-BFE5-A4167D643966 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/SCXcodeSwitchExpander.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2017-01-03 15:15:54.661 xcodebuild[43952:479696] [MT] PluginLoading: Required plug-in compatibility UUID E0A62D1F-3C18-4D74-BFE5-A4167D643966 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/ObjectGraph.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2017-01-03 15:15:54.662 xcodebuild[43952:479696] [MT] PluginLoading: Required plug-in compatibility UUID E0A62D1F-3C18-4D74-BFE5-A4167D643966 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/KSHObjcUML.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2017-01-03 15:15:54.662 xcodebuild[43952:479696] [MT] PluginLoading: Required plug-in compatibility UUID E0A62D1F-3C18-4D74-BFE5-A4167D643966 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/FuzzyAutocomplete.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2017-01-03 15:15:54.662 xcodebuild[43952:479696] [MT] PluginLoading: Required plug-in compatibility UUID E0A62D1F-3C18-4D74-BFE5-A4167D643966 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs
▸ Building CustomDatePicker/CustomDatePicker [Debug]
▸ Check Dependencies
▸ Build Succeeded
Capturing using xcpretty...
Starting translating 0 files 
.
Starting analysis...

legend:
  "F" analyzing a file
  "." analyzing a procedure

Found 0 source files in /Users/evgzor/Dropbox/Projects/CustomDatePickerView/CustomDatePickerNoArc/infer-out


  No issues found  

Is it correct behavior?
 Also please provide any support address on website http://fbinfer.com/support.html#need-help? "contact us" does not work. I just wanted to integrate to Xcode in the build script.

**Comment by evgzor** [comment] 2017-01-03 12:55
I integrated into Xcode and got:  https://gyazo.com/3611c911ca1207957edc816a80125fb8
Which different in compare what I've got above

**Comment by evgzor** [comment] 2017-01-03 15:09
I made Xcode integration and it works now with script:
if [ "${CONFIGURATION}" = "Infer" ]; then
PROJECT_BUILD_DIR=${PROJECT_DIR}/build
INFER_OUT_DIR=${PROJECT_DIR}/infer-out
if [ -d "$PROJECT_BUILD_DIR" ]; then
echo build dir exist: ${PROJECT_BUILD_DIR}
fi
rm -r -f ${PROJECT_BUILD_DIR} ${INFER_OUT_DIR}
export LC_ALL=en_US.UTF-8
PLATFORM="$(echo "$EFFECTIVE_PLATFORM_NAME" | sed 's/-//g')"
RUN_INFER_CLI="$(echo infer -- xcodebuild -target ${EXECUTABLE_NAME} -configuration Release -sdk ${PLATFORM})"
${RUN_INFER_CLI}
rm -r -f ${PROJECT_BUILD_DIR} ${INFER_OUT_DIR}
fi

Problem in "build" and "infer-out" directories I guess.

**Comment by akotulski** [comment] 2017-01-12 11:02
Looks like all issues were resolved. Don't hesitate to open new issues if you encounter problems

**Closed by akotulski** 2017-01-12 11:02 UTC
