### ISSUE TITLE
I'm failed with helloworld example 

### ISSUE THREAD

**Issue by lichanghong** [facebook/infer#1173] opened 2019-10-29 13:38 UTC
hello.m:1:9: fatal error: 'Foundation/Foundation.h' file not found
#import <Foundation/Foundation.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
Error: the following clang command did not run successfully:
    /usr/local/Cellar/infer/0.15.0/lib/infer/facebook-clang-plugins/clang/install/bin/clang
    @/var/folders/m0/b6__78jj2gjcgfxlbjmzmsm80000gn/T/clang_command_.tmp.9452cb.txt
  ++Contents of '/var/folders/m0/b6__78jj2gjcgfxlbjmzmsm80000gn/T/clang_command_.tmp.9452cb.txt':
    "-cc1" "-load"
    "/usr/local/Cellar/infer/0.15.0/lib/infer/infer/bin/../../facebook-clang-plugins/libtooling/build/FacebookClangPlugin.dylib"
    "-add-plugin" "BiniouASTExporter" "-plugin-arg-BiniouASTExporter" "-"
    "-plugin-arg-BiniouASTExporter" "PREPEND_CURRENT_DIR=1"
    "-plugin-arg-BiniouASTExporter" "MAX_STRING_SIZE=65535" "-cc1" "-triple"
    "x86_64-apple-macosx10.14.0" "-Wdeprecated-objc-isa-usage"
    "-Werror=deprecated-objc-isa-usage" "-emit-obj" "-mrelax-all"
    "-disable-free" "-disable-llvm-verifier" "-discard-value-names"
    "-main-file-name" "hello.m" "-mrelocation-model" "pic" "-pic-level" "2"
    "-mthread-model" "posix" "-mdisable-fp-elim" "-masm-verbose"
    "-munwind-tables" "-target-cpu" "penryn" "-dwarf-column-info"
    "-debugger-tuning=lldb" "-target-linker-version" "351.8"
    "-coverage-notes-file"
    "/Users/ziroom/Documents/ziroom/wireless/inferT/hello.gcno"
    "-resource-dir"
    "/usr/local/Cellar/infer/0.15.0/lib/infer/facebook-clang-plugins/clang/install/lib/clang/7.0.0"
    "-include"
    "/usr/local/Cellar/infer/0.15.0/lib/infer/infer/bin/../lib/clang_wrappers/global_defines.h"
    "-Wno-ignored-optimization-argument" "-Wno-everything"
    "-fdebug-compilation-dir"
    "/Users/ziroom/Documents/ziroom/wireless/inferT" "-ferror-limit" "19"
    "-fmessage-length" "0" "-stack-protector" "1" "-fblocks"
    "-fencode-extended-block-signature" "-fobjc-runtime=macosx-10.14.0"
    "-fobjc-exceptions" "-fexceptions" "-fmax-type-align=16"
    "-fdiagnostics-show-option" "-o" "hello.o" "-x" "objective-c" "hello.m"
    "-O0" "-include"
    "/usr/local/Cellar/infer/0.15.0/lib/infer/infer/bin/../lib/clang_wrappers/global_defines.h"
    "-Wno-everything"

**Comment by lichanghong** [comment] 2019-10-29 14:03
bash-3.2$ clang -v
Apple clang version 11.0.0 (clang-1100.0.33.8)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by lichanghong** [comment] 2019-10-29 14:04
Infer version v0.15.0

**Comment by jaseemabid** [comment] 2019-10-31 23:22
@lichanghong This *maybe* be a duplicate of https://github.com/facebook/infer/issues/1026#issuecomment-548591456, try with `export SDKROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk` ?

**Comment by lichanghong** [comment] 2019-11-01 03:18
> @lichanghong This _maybe_ be a duplicate of [#1026 (comment)](https://github.com/facebook/infer/issues/1026#issuecomment-548591456), try with `export SDKROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk` ?

thanks for your response. I have read #1026 carefully. but ,this method don't resolve my problem. 
I have found a method to resole this problem as below:
#  infer -- clang -isysroot $(xcode-select -p)/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk -target x86_64-apple-darwin14 -mios-simulator-version-min=8.2 -x objective-c -c -fblocks hello.m

**Closed** 2019-11-01 03:19 UTC

**Comment by jvillard** [comment] 2019-11-06 12:49
Note that upgrading to 0.17.0 should solve the issue too.
