### ISSUE TITLE
I want to add a custom rule, how to do?

### ISSUE THREAD

**Issue by LRH-iOS** [facebook/infer#1554] opened 2021-11-09 08:34 UTC
I want to add a custom rule.
rule: analyze .ipa or .app to find a specific string. My questions are as follows:(string, such as "strlen")

How many specific strings are displayed?
In which class does it run?
How can I customize this rule?

**Comment by jvillard** [comment] 2021-11-09 10:30
duplicate of #1550

**Closed by jvillard** 2021-11-09 10:30 UTC
