### ISSUE TITLE
Not recognizing known sRGB profile that has been edited

### ISSUE THREAD

**Issue by qiaobacmm** [facebook/infer#81] opened 2015-06-18 08:33 UTC
16:31:55.585 [ERROR] [org.gradle.api.Project] /Users/jiuping/Desktop/Mogu/Minicooper4android/app/src/main/res/drawable-xhdpi/draft_box.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited

16:32:07.632 [ERROR] [system.err] 注: 某些输入文件使用或覆盖了已过时的 API。
16:32:07.633 [ERROR] [system.err] 注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
16:32:07.633 [ERROR] [system.err] 注: 某些输入文件使用了未经检查或不安全的操作。
16:32:07.633 [ERROR] [system.err] 注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。

**Comment by irpap** [comment] 2015-06-18 12:16
Hi, which command did you run? 
Also, do you get this error when building your project with gradle (without using infer)?

**Comment by Ken-NET** [comment] 2015-06-18 14:03
Hi Irpap, I have the same errors. And I run "infer -- ./gradlew build" but it seems all src files are skipped.

**Comment by martinoluca** [comment] 2015-06-18 14:16
Hello @Ken-NET and @qiaobacmm, could you please provide us some instructions on how to reproduce your issue?
Thanks.

**Comment by jvillard** [comment] 2015-06-22 14:55
Hi @qiaobacmm and @Ken-NET, this looks like a possible duplicate of #18. Another possibility is that you need to clean your project before running Infer:

```shell
infer -- ./gradlew clean
infer -- ./gradlew build
```

**Closed** 2015-07-02 12:23 UTC
Labels: java
