### ISSUE TITLE
Infer 0.17.0 has internal error InferBase.SqliteUtils.Error

### ISSUE THREAD

**Issue by pmatos** [facebook/infer#1221] opened 2020-02-12 15:10 UTC
Version 0.17.0 on a Ubuntu 18.04 Linux - not a container.

Trying to check [racket](https://github.com/racket/racket).

So, I try:
```
$ git clone https://github.com/racket/racket
$ cd racket/src
$ ./configure 
$ infer capture -- make
$ infer run infer analyze -j 16 --purity --bufferoverrun --racerd --quandary
```

To obtain the error:
```
Uncaught Internal Error: ("InferBase.SqliteUtils.Error(\"load bind proc name: MISUSE (bad parameter or other API misuse)\")")
Error backtrace:
Raised at file "base/SqliteUtils.ml" (inlined), line 12, characters 45-62
Called from file "format.ml", line 1364, characters 4-36
Called from file "IR/Procdesc.ml", line 880, characters 6-139
Called from file "base/ResultsDatabase.ml", line 106, characters 15-24
Called from file "camlinternalLazy.ml", line 27, characters 17-27
Re-raised at file "camlinternalLazy.ml", line 34, characters 4-11
Called from file "src/list.ml", line 226, characters 12-15
Called from file "backend/ondemand.ml" (inlined), line 339, characters 6-29[15.8s] racket/src/jitcommon.c: scheme_do_generate_common
Called from file "backend/ondemand.ml" (inlined), line 357, characters 22-4985.3s] >>>>racket/src/jitinline.c: scheme_generate_inlined_binary
Called from file "backend/ondemand.ml", line 384, characters 2-61ry
Called from file "backend/ondemand.ml" (inlined), line 393, characters 12-45337.1s] idle
Called from file "list.ml", line 106, characters 12-15
Called from file "list.ml" (inlined), line 104, characters 13-64
Called from file "list.ml" (inlined), line 106, characters 17-25
Called from file "list.ml" (inlined), line 104, characters 13-64
Called from file "src/list0.ml" (inlined), line 26, characters 40-75
Called from file "backend/ondemand.ml" (inlined), line 395, characters 2-54
Called from file "backend/ondemand.ml", line 406, characters 2-64
Called from file "backend/InferAnalyze.ml", line 26, characters 8-49
Called from file "base/Logging.ml", line 218, characters 60-64
Called from file "backend/InferAnalyze.ml", line 53, characters 8-47
Called from file "base/ProcessPool.ml", line 329, characters 12-19
Re-raised at file "istd/IExn.ml", line 18, characters 15-63
Called from file "base/ProcessPool.ml", line 331, characters 10-427
Called from file "base/ProcessPool.ml" (inlined), line 311, characters 19-1023
Called from file "base/ProcessPool.ml", line 384, characters 6-81
Called from file "base/ProcessPool.ml" (inlined), line 409, characters 8-79
Called from file "array.ml" (inlined), line 51, characters 22-27
Called from file "base/ProcessPool.ml", line 408, characters 4-117
Called from file "backend/Tasks.ml", line 36, characters 6-224
Called from file "backend/InferAnalyze.ml", line 129, characters 6-109
Called from file "backend/InferAnalyze.ml", line 172, characters 14-34
Called from file "integration/Driver.ml", line 333, characters 2-34
Called from file "integration/Driver.ml" (inlined), line 340, characters 2-32
Called from file "integration/Driver.ml", line 430, characters 9-39
Called from file "base/Utils.ml", line 398, characters 16-20
Called from file "scuba/ScubaLogging.ml", line 66, characters 29-44
Called from file "infer.ml", line 21, characters 2-47
Called from file "base/Utils.ml", line 398, characters 16-20
Called from file "scuba/ScubaLogging.ml", line 66, characters 29-44
Called from file "infer.ml" (inlined), line 25, characters 22-94
Called from file "infer.ml", line 135, characters 8-26

Run the command again with `--keep-going` to try and ignore this error.
Internal Error: Subprocess 10: see backtrace above
Error backtrace:
Raised at file "src/core_unix.ml" (inlined), line 50, characters 4-43
Called from file "src/core_unix.ml" (inlined), line 930, characters 4-246
Called from file "src/core_unix.ml" (inlined), line 959, characters 2-34
Called from file "base/ProcessPool.ml", line 149, characters 10-30
Re-raised at file "base/Die.ml" (inlined), line 26, characters 8-56
Called from file "base/Die.ml", line 32, characters 6-39
Called from file "list.ml" (inlined), line 106, characters 12-15
Called from file "src/list0.ml" (inlined), line 26, characters 40-75
Called from file "base/ProcessPool.ml" (inlined), line 233, characters 5-1023
Called from file "base/ProcessPool.ml", line 232, characters 2-1023
Called from file "base/ProcessPool.ml", line 426, characters 4-31
Called from file "base/ProcessPool.ml", line 434, characters 16-24
Called from file "backend/InferAnalyze.ml", line 132, characters 24-47
Called from file "backend/InferAnalyze.ml", line 172, characters 14-34
Called from file "integration/Driver.ml", line 333, characters 2-34
Called from file "integration/Driver.ml" (inlined), line 340, characters 2-32
Called from file "integration/Driver.ml", line 430, characters 9-39
Called from file "base/Utils.ml", line 398, characters 16-20
Called from file "scuba/ScubaLogging.ml", line 66, characters 29-44
Called from file "infer.ml", line 21, characters 2-47
Called from file "base/Utils.ml", line 398, characters 16-20
Called from file "scuba/ScubaLogging.ml", line 66, characters 29-44
Called from file "infer.ml" (inlined), line 25, characters 22-94
Called from file "infer.ml", line 135, characters 8-26

Run the command again with `--keep-going` to try and ignore this error.
```

**Comment by ngorogiannis** [comment] 2020-02-13 11:37
Please see #1081.

Duplicate of #1081

**Comment by ngorogiannis** [comment] 2020-02-13 11:38
Duplicate of #1081

**Closed by ngorogiannis** 2020-02-13 11:38 UTC
