### ISSUE TITLE
cannot compile clang

### ISSUE THREAD

**Issue by yinle2002** [facebook/infer#517] opened 2016-12-03 23:53 UTC
When I execute facebook-clang-plugins/clang/setup.sh to compile clang, the error presents as follows.

      make: *** [all] Error 2
      strip: '/home/parallels/opensrc/infer/facebook-clang-plugins/clang/install/bin/*': No such file
      find: `/home/parallels/opensrc/infer/facebook-clang-plugins/clang/install/lib': No such file or directory

There are also many 'undefined reference' warnings, for example:

     CMakeFiles/cxx.dir/__/src/debug.cpp.o: In function `std::__1::__get_db()':
     debug.cpp:(.text._ZNSt3__18__get_dbEv+0x21): undefined reference to `__cxa_guard_acquire'
     debug.cpp:(.text._ZNSt3__18__get_dbEv+0x4c): undefined reference to `__cxa_guard_release'
     ...

**Comment by jberdine** [comment] 2016-12-04 00:02
Can you please provide more information? Please include:
1. the version of infer
2. the full history of commands you used to run infer
3. the full output (please use https://gist.github.com/ or equivalent)

**Comment by akotulski** [comment] 2016-12-04 10:24
Please include OS you use and version of gcc/clang you have on your system as well

**Comment by yinle2002** [comment] 2016-12-04 14:31
I am building the infer of the latest version in github on ubuntu 14.04. The ubuntu OS is installed in the virtual machine Parallels(TM) on Mac OS (intel Core i7 cpu).

The command 'uname -a' printed information as follows.
      Linux ubuntu 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

I run the following commands:
     git clone https://github.com/facebook/infer.git
     cd infer
     ./build-infer.sh java
It succeeded. 

Then I run './build-infer.sh clang' and it failed. The clang version 

Then I run the following commands:
     cd facebook-clang-plugins/clang
     rm installed.version
     ./setup.sh

    The output of setup.sh is in 
'https://gist.github.com/yinle2002/027fefccdd408f7105aa07bbe8ba5675'

     However, command './setup.sh' returned 0 and produced file installed.version, whose contents is as follows:
0fe7f0565f6646d5f262daea00d9dae58fd44dc7b073e24707a987b3282c6d47 ?src/clang-4.0.tar.xz
78bdffeea7b0a38eb78dd9c5f43a1718d2d5024bd090b6b83c237b1c5cf35c72 ?setup.sh

So I think the clang version is 4.0.

**Comment by akotulski** [comment] 2016-12-05 14:31
I meant your host compiler that is used to compile that clang - from your gist it looks like you have `gcc 4.8.4` which should be new enough to compile clang.
I've seen those errors before but I thought they were fixed (https://github.com/facebook/facebook-clang-plugins/blob/master/clang/setup.sh#L82 should do it)
I'm going to try and reproduce the problem on local VM, but it may take some time

**Comment by akotulski** [comment] 2016-12-05 14:46
@yinle2002 could you check if you have c++ libraries installed?
Simply run following command: `apt list | grep libstdc++`

**Comment by akotulski** [comment] 2016-12-05 18:13
I reproduced the problem on my VM. I was unable to find the fix yet, but I'm planning to look into it more. Stay tuned

**Comment by akotulski** [comment] 2016-12-06 11:20
Issue reproduces with newest `clang-3.9.1` release. I created [bug report](https://llvm.org/bugs/show_bug.cgi?id=31291), hopefully they will have a fix/workaround for it

**Comment by leo-yinle** [comment] 2016-12-07 10:16
Hi @akotulski 

Thank you for your response.

In  [https://llvm.org/bugs/show_bug.cgi?id=31291](url), the bug is expected to be closed. However, how should I do to make 'setup.sh' work? Is there any concrete guide?

**Comment by leo-yinle** [comment] 2016-12-07 10:19
Hi @akotulski

Thank you for your response.

In https://llvm.org/bugs/show_bug.cgi?id=31291, the bug is expected to be closed. However, I still wonder how should I do to make 'setup.sh' work? Is there any concrete guide?

**Comment by akotulski** [comment] 2016-12-07 13:19
I'm planning to update source code of clang we use. Then it should work for you.

**Comment by KihongHeo** [comment] 2016-12-08 04:22
Hi @akotulski  and @leo-yinle ,
I also have a problem but I am not sure it is the same as the one above. 
In my case, I got the following error messages during the clang compilation.

```
[ 51%] Linking CXX static library ../libLLVMAnalysis.a
make[3]: Leaving directory `/tmp/clang-setup.VeTyKm/build'
[ 51%] Built target LLVMAnalysis
make[2]: Leaving directory `/tmp/clang-setup.VeTyKm/build'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/tmp/clang-setup.VeTyKm/build'
strip: '/home/khheo/project/infer_ropas/facebook-clang-plugins/clang/install/bin/*': No such file
find: `/home/khheo/project/infer_ropas/facebook-clang-plugins/clang/install/lib': No such file or directory
/tmp/clang-setup.VeTyKm ~/project/infer_ropas
~/project/infer_ropas
make -C /home/khheo/project/infer_ropas/facebook-clang-plugins/libtooling all \
          CC=clang CXX=clang++ \
          CFLAGS="-g -O2" CXXFLAGS="-g -O2" \
          CPP="clang -E" LDFLAGS="" LIBS="" \
          LOCAL_CLANG=/home/khheo/project/infer_ropas/facebook-clang-plugins/clang/install/bin/clang \
          CLANG_PREFIX=/home/khheo/project/infer_ropas/facebook-clang-plugins/clang/install \
          CLANG_INCLUDES=/home/khheo/project/infer_ropas/facebook-clang-plugins/clang/install/include
make[1]: Entering directory `/home/khheo/project/infer_ropas/facebook-clang-plugins/libtooling'
make[1]: *** No rule to make target `build/SimplePluginASTAction.o', needed by `build/FacebookClangPlugin.dylib'.  Stop.
make[1]: Leaving directory `/home/khheo/project/infer_ropas/facebook-clang-plugins/libtooling'
make: *** [clang_plugin] Error 2
```

I use 
```
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty
khheo@rec:~/project/infer_ropas$ gcc --version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by akotulski** [comment] 2016-12-08 13:24
I just committed https://github.com/facebook/infer/commit/3096e8448b124607dc0a0a0df99795711502683f to fix that problem. Please fetch infer's master and remember to update `facebook-clang-plugins` submodule by running `git submodule update`

@KihongHeo by the fact that you are using ubuntu 14.04 I'd say it's likely the same issue. Please try again with newest version of infer.

**Closed by akotulski** 2016-12-08 13:24 UTC
