### ISSUE TITLE
Getting OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by mshukla19** [facebook/infer#79] opened 2015-06-17 11:40 UTC
I ran infer and got this error after 15 mins. I'm using this on OSX 10.8.4  and on an android project with gradle. The command used was - 

infer -- ./gradlew build

Note - ( I ran infer on the same project on a different mac with OSX Yosemite and it worked fine and showed me the output).

DUMP Below -

Starting analysis (Infer version v0.1.0)
Traceback (most recent call last):
  File "/Downloads/holidify/infer-osx-v0.1.0/infer/infer/bin/infer", line 142, in <module>
    main()
  File "/Downloads/holidify/infer-osx-v0.1.0/infer/infer/bin/infer", line 138, in main
    analysis.analyze_and_report()
  File "/Downloads/holidify/infer-osx-v0.1.0/infer/infer/bin/inferlib.py", line 613, in analyze_and_report
    if self.analyze() == os.EX_OK:
  File "/Users/shashwat/Downloads/holidify/infer-osx-v0.1.0/infer/infer/bin/inferlib.py", line 501, in analyze
    self.args.analyzer
  File "/Users/shashwat/Downloads/holidify/infer-osx-v0.1.0/infer/infer/bin/inferlib.py", line 309, in run_command
    return subprocess.check_call(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 506, in check_call
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 493, in call
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 679, in __init__
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1228, in _execute_child
OSError: [Errno 2] No such file or directory

**Comment by martinoluca** [comment] 2015-06-17 12:45
Hello @mshukla19,
could you please try running the same command (`./gradlew build`) without `infer --` ?

**Comment by alvarofe** [comment] 2015-06-17 13:59
I'm getting the same error

```
gcc -c  -MD   -fPIC -g -Wall -D__UNIX__=1 -I/Users/alvaro_fe/Projects/Reverse/radare2/r2/libr/../shlr/zip/include -DLIBDIR=\"/usr/lib\" -I/Users/alvaro_fe/Projects/Reverse/radare2/r2/libr/..//libr/include -DR2_BIRTH=\"`date +%Y-%m-%d`\"  -DR2_GITTIP=\"859fadb38c775e1e4881832c40561f456520a4d7\" -DR2_GITTAP=\"0.9.9-85-g859fadb\" -o r2agent.o r2agent.c
gcc r2agent.o -L.. -o r2agent      -L/Users/alvaro_fe/Projects/Reverse/radare2/r2/libr/socket -L/Users/alvaro_fe/Projects/Reverse/radare2/r2/libr/cons -L/Users/alvaro_fe/Projects/Reverse/radare2/r2/libr/util -lr_socket -lr_cons -lr_util -fPIC /Users/alvaro_fe/Projects/Reverse/radare2/r2/libr/../shlr/zip/librz.a
Traceback (most recent call last):
  File "/Users/alvaro_fe/Projects/Reverse/infer/infer/bin/infer", line 141, in <module>
    main()
  File "/Users/alvaro_fe/Projects/Reverse/infer/infer/bin/infer", line 137, in main
    analysis.analyze_and_report()
  File "/Users/alvaro_fe/Projects/Reverse/infer/infer/bin/inferlib.py", line 613, in analyze_and_report
    if self.analyze() == os.EX_OK:
  File "/Users/alvaro_fe/Projects/Reverse/infer/infer/bin/inferlib.py", line 489, in analyze
    self.args.analyzer
  File "/Users/alvaro_fe/Projects/Reverse/infer/infer/bin/inferlib.py", line 309, in run_command
    return subprocess.check_call(cmd)
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Only doing `make` works fine. I will try in Linux asap.

Thanks in advanced ;)

**Comment by alvarofe** [comment] 2015-06-17 14:00
btw

```
 alvaro_fe@macbook  ~/Projects/Reverse/radare2/r2   infer ± sw_vers
ProductName:    Mac OS X
ProductVersion: 10.10.3
BuildVersion:   14D136
```

**Comment by akotulski** [comment] 2015-06-17 16:26
@alvarofe it looks like infer script can't find InferAnalyze binary in bin/ directory
/Users/alvaro_fe/Projects/Reverse/infer/infer/bin/

would you mind running following command:
ls -l /Users/alvaro_fe/Projects/Reverse/infer/infer/bin/

**Comment by alvarofe** [comment] 2015-06-17 20:30
Yeah, that file is missing

```
 alvaro_fe@macbook  ~/Projects/Reverse/infer/infer/bin   master  ls -l
total 256
-rwxr-xr-x  1 alvaro_fe  staff  16660 17 jun 13:31 BuckAnalyze
-rwxr-xr-x  1 alvaro_fe  staff   4604 17 jun 13:31 infer
-rwxr-xr-x  1 alvaro_fe  staff    479 17 jun 13:31 inferJ
-rwxr-xr-x  1 alvaro_fe  staff    638 17 jun 13:31 inferTest
-rwxr-xr-x  1 alvaro_fe  staff   7680 17 jun 13:31 inferTraceBugs
-rw-r--r--  1 alvaro_fe  staff  21907 17 jun 13:31 inferlib.py
-rw-r--r--  1 alvaro_fe  staff  20518 17 jun 14:05 inferlib.pyc
-rw-r--r--  1 alvaro_fe  staff   1665 17 jun 13:31 jwlib.py
-rw-r--r--  1 alvaro_fe  staff   2025 17 jun 14:05 jwlib.pyc
-rw-r--r--  1 alvaro_fe  staff  10126 17 jun 13:31 utils.py
-rw-r--r--  1 alvaro_fe  staff  12390 17 jun 14:05 utils.pyc
```

Some problem while compiling infer?

**Comment by akotulski** [comment] 2015-06-17 22:08
@alvarofe where did you get binaries from? Could you try redownloading them again from our github releases page and try again? It is there for me.
https://github.com/facebook/infer/releases

**Comment by mshukla19** [comment] 2015-06-18 12:23
@akotulski @martinoluca I tried running the ./gradlew build without infer and it builds successfuly. i also checked that if i had InferAnalyze and it also present. Anything else that i can do?

**Comment by alvarofe** [comment] 2015-06-20 10:14
I followed the instructions from `https://github.com/facebook/infer/blob/master/INSTALL.md` but the release is working fine now. Thanks @akotulski

**Comment by jvillard** [comment] 2015-06-22 14:52
@mshukla19: your problem may be a duplicate of #30. Please try installing java and javac version 1.7 if you have a different version (see the outputs of `java -version` and `javac -version`). This is a temporary workaround until we get the problem fixed in a third-party library used to parse Java bytecode inside Infer.

Also, you may want to upgrade Infer to [the latest version](https://github.com/facebook/infer/releases/latest/) (currently 0.1.1), which fixed a number of issues.

Feel free to re-open this task if neither of these fixed your problem!

**Closed by jvillard** 2015-06-22 14:52 UTC
