### ISSUE TITLE
iOS app build fails when using infer

### ISSUE THREAD

**Issue by legate** [facebook/infer#39] opened 2015-06-12 19:29 UTC
When I build my app like this it succeeds: `xcodebuild -workspace "foo" -scheme "bar" -configuration "baz" -sdk "iphonesimulator"`

However when I use it with infer, I get a compilation error.

`infer -- xcodebuild -workspace "foo" -scheme "bar" -configuration "baz" -sdk "iphonesimulator"` gives me:

    error: use of
          '@import' when modules are disabled
    @import UIKit;

Does infer affect the build process?

**Comment by dulmarod** [comment] 2015-06-12 19:50
Have a look in the issues, there is already a similar report. We are working on it.

Sent from my Android phone using Symantec TouchDown (www.symantec.com)

-----Original Message-----

**Comment by jvillard** [comment] 2015-06-12 20:12
Closing, duplicate of #2.

**Closed by jvillard** 2015-06-12 20:12 UTC

**Comment by Rosepotato** [comment] 2015-06-17 01:42
I have the same problem like legate said.
When  I use following command to compile, it works ok. 
xcodebuild \
-workspace Spond.xcworkspace \
-scheme Spond \
-sdk iphonesimulator8.1 \
-configuration Debug \
-destination 'name=iPhone 6,OS=8.1' \
build

But when I use infer like following, compile error happened.
command use:
infer -- xcodebuild \
-workspace Spond.xcworkspace \
-scheme Spond \
-sdk iphonesimulator8.1 \
-configuration Debug \
-destination 'name=iPhone 6,OS=8.1' \
build

compile error:
The following build commands failed:
	CompileC /Users/spond/Library/Developer/Xcode/DerivedData/Spond-eyieenlshldlysecdqubtdtimfnb/Build/Intermediates/Pods.build/Debug-iphonesimulator/Pods-TapkuLibrary.build/Objects-normal/x86_64/CAAnimation+TKAnimation.o TapkuLibrary/src/TapkuLibrary/CAAnimation+TKAnimation.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/spond/Library/Developer/Xcode/DerivedData/Spond-eyieenlshldlysecdqubtdtimfnb/Build/Intermediates/Pods.build/Debug-iphonesimulator/Pods-TapkuLibrary.build/Objects-normal/x86_64/CAKeyframeAnimation+TKAnimation.o TapkuLibrary/src/TapkuLibrary/CAKeyframeAnimation+TKAnimation.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)
