### ISSUE TITLE
[Bug] C macros -- EOF in marshal.ml

### ISSUE THREAD

**Issue by Isweet** [facebook/infer#1039] opened 2019-01-02 19:37 UTC
It seems like some issue with macros in C is causing Infer to barf.

defs.h
```
#define THREE 3
```

foo.c
```
#include "defs.h"

int main() {
    return THREE + 2;
}
```

Compiling this on its own with `clang` is fine.

```
$ clang --version
clang version 7.0.0-3 (tags/RELEASE_700/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
$ clang -o foo foo.c
$ ./foo
$ echo $?
5
```

but with Infer, there are a bunch of identical errors being thrown by forked subprocesses.

```
$ ~/projects/infer/infer/bin/infer --version
Infer version v0.15.0-c09068e3b
Copyright 2009 - present Facebook. All Rights Reserved.
$ ~/projects/infer/infer/bin/infer-run -- clang -o foo foo.c
Capturing in make/cc mode...
Found 1 source file to analyze in /home/ian/projects/scratch/macro-bug/infer-out
1/1 [###########################################################
Uncaught Internal Error: End_of_file
Error backtrace: main
Raised by primitive operation at file "marshal.ml" (inlined), line 43, characters 0-60
Called from file "base/ProcessPool.ml", line 247, characters 16-46
Called from file "base/ProcessPool.ml", line 196, characters 8-30
Called from file "base/ProcessPool.ml" (inlined), line 194, characters 19-694
Called from file "base/ProcessPool.ml", line 251, characters 6-60
Called from file "base/ProcessPool.ml" (inlined), line 268, characters 46-92
Called from file "array.ml" (inlined), line 51, characters 22-27
Called from file "base/ProcessPool.ml", line 268, characters 14-93
Called from file "backend/Tasks.ml", line 47, characters 6-202
Called from file "backend/InferAnalyze.ml", line 98, characters 17-77
Called from file "integration/Driver.ml", line 311, characters 2-34
Called from file "integration/Driver.ml" (inlined), line 318, characters 2-32
Called from file "integration/Driver.ml", line 407, characters 9-39
Called from file "infer.ml", line 21, characters 2-47
Called from file "infer.ml", line 131, characters 8-54
```

Replacing the macro use `THREE` in `foo.c` with the literal `3` fixes the issue.

Is there something I'm doing wrong?

**Comment by Isweet** [comment] 2019-01-02 19:47
This is not specific to macros. I've also tried changing to:

defs.h
```
int three() { return 3; }
```

foo.c
```
#include "defs.h"

int main() {
    return three() + 2;
}
```

**Comment by jvillard** [comment] 2019-01-03 12:15
We cannot reproduce the issue. Looks like the crash is caused by deserialising from the unix pipe between the master process and the slaves, so running with `-j 1` should remove the crash (but also the parallelism in the analysis). Just to get more data: what system and version of OCaml are you running on?

**Comment by Isweet** [comment] 2019-01-03 15:41
I suspect it is my hardware / OS. Here are my specs:

OS: Ubuntu 18.10 x86_64
Host: 20M9CTO1WW ThinkPad P52
Kernel: 4.19.11-041911-generic
CPU: Intel Xeon E-2176M (12) @ 4.400
OCaml: ocaml-variants.4.07.1+flambda

**Comment by Isweet** [comment] 2019-01-03 15:47
And now after a restart, I also cannot replicate the bug... I suppose it is safe to close? Very strange.

**Comment by jvillard** [comment] 2019-01-03 15:52
Very strange indeed! I think we can close this and re-open if it happens again.

**Closed** 2019-02-04 15:48 UTC
