### ISSUE TITLE
Infer v0.9.4 fails to analyze openssh-portable-V_7_2_P2

### ISSUE THREAD

**Issue by Guoanshisb** [facebook/infer#586] opened 2017-02-23 23:19 UTC
Hey guys,

Infer throws some errors and fails to analyze openssh-portable-V_7_2_P2 (`infer -- make -j64`).  The useful error message may be,

```
Uncaught exception:

  "Assert_failure backend/interproc.ml:1448:10"

Raised at file "backend/interproc.ml", line 1448, characters 10-22
```

It's weird that Infer v0.8.1 works fine on this project.

Shaobo

**Comment by jeremydubreil** [comment] 2017-02-24 18:02
Hi @Guoanshisb,

Thanks for reporting this. 

Can you check if you get the same error with the latest release v0.10.0 ?

**Comment by Guoanshisb** [comment] 2017-02-24 22:06
Yes, it seems v.10.0 also doesn't work. The following are the relevant messages,

```
  "Assert_failure backend/interproc.ml:1433:10"

Raised at file "backend/interproc.ml", line 1433, characters 10-22
Called from file "list.ml", line 73, characters 12-15
Called from file "backend/interproc.ml", line 1447, characters 2-216
Called from file "backend/InferAnalyze.re", line 30, characters 4-33
Called from file "backend/InferAnalyzeExe.re", line 40, characters 2-43
.make: *** [cl131] Error 2

Uncaught exception:

  (Unix.Exit_or_signal (Exit_non_zero 2))

Raised at file "src/error.ml", line 7, characters 20-30
Called from file "backend/infer.ml", line 340, characters 25-43
Called from file "backend/infer.ml", line 456, characters 2-21
```

**Comment by jeremydubreil** [comment] 2017-02-25 07:05
Thanks for checking with the latest release. So the issue comes for here: https://github.com/facebook/infer/blob/957b67fa878f297f12a9bdb3dcf13fd962856e2a/infer/src/backend/interproc.ml#L1433

However, I cannot reproduce the error locally when running Infer on `openssh-7.2p2`

**Comment by Guoanshisb** [comment] 2017-02-25 07:27
@jeremydubreil  Thanks for looking into it. I just downloaded the openssh source code again and ran infer.  And I got the same error again.

The commands I used are,

```
/mnt/local/openssh-7.2p2$ ./configure
/mnt/local/openssh-7.2p2$ infer -- make -j64
```

I was wondering if I invoked Infer correctly here.

**Comment by jeremydubreil** [comment] 2017-02-25 18:46
This is the expected way to run Infer. I also tried with `infer -- make -j64` but did not observe the same issue. I look into what can cause the files to not be found.

**Comment by Guoanshisb** [comment] 2017-02-26 01:59
@jeremydubreil Thanks a lot for your help.

**Comment by Guoanshisb** [comment] 2017-03-02 06:18
@jeremydubreil I would like to share some update on my side. I tried to build Infer v0.10.0 on Windows subsystem for Linux and it worked on openssh. I guess that I must have messed up some environment setups in another machine. Do you think the clang version matters?

**Comment by jeremydubreil** [comment] 2017-03-02 17:36
Thanks for the update. Infer uses its own version of clang. I may be wrong but the version installed on the system should not matter. @jvillard: is this correct ?

**Comment by Guoanshisb** [comment] 2017-03-02 17:38
Yes, my guess is also that clang version shouldn't matter. It's weird that I got the same errors again after some experiments. Now I'm trying to use the docker image. It seems to work pretty smoothly.

**Comment by Guoanshisb** [comment] 2017-03-02 17:41
May I ask another question here? If I increase the `--iterations` flag, Infer will probably get more precise, right?

**Comment by xennygrimmato** [comment] 2017-03-02 17:52
I have faced the same issue while analyzing a project with a large number of Java files.
@jeremydubreil Do you think it could be because of that?

**Comment by jvillard** [comment] 2017-03-03 10:54
>  Infer uses its own version of clang. I may be wrong but the version installed on the system should not matter. @jvillard: is this correct ?

@jeremydubreil correct.

> If I increase the --iterations flag, Infer will probably get more precise, right?

It will spend more time on procedures before giving up. That often translates into more precision but your mileage may vary.

@xennygrimmato size of chains of function calls do not matter thanks to the way the interprocedural analysis is implemented: a caller only knows to read the spec of the callees, it doesn't need to go and look at their code.

**Comment by sblackshear** [comment] 2017-04-19 23:41
Closing since it works in Docker/we can't reproduce locally.

**Closed by sblackshear** 2017-04-19 23:41 UTC
