### ISSUE TITLE
Infer 0.9.4 does not work with preprocessed C code

### ISSUE THREAD

**Issue by KihongHeo** [facebook/infer#512] opened 2016-11-27 09:23 UTC
Hi Infer Team,

0.9.4 does not work on some programs that can be successfully analyzed by 0.9.3.
Below, I put the messages.

--
$ ~/project/infer-linux64-v0.9.3/infer/bin/infer -- gcc -c time-1.7.c
Infer version v0.9.3
Copyright 2009 - present Facebook. All Rights Reserved.
Starting analysis (Infer version v0.9.3)

legend:
  "F" analyzing a file
  "." analyzing a procedure

F
Analyzed 1 file

  No issues found

$ ~/project/infer-linux64-v0.9.4/infer/bin/infer -- gcc -c time-1.7.c
Capturing in make/cc mode...
Starting analysis...

legend:
  "F" analyzing a file
  "." analyzing a procedure

Found 0 source files in /home/khheo/project/InferExperiment/infer-out

  No issues found

--

I attached the source code (time-1.7.c). This is a preprocessed C code with "gcc -E" and CIL (http://people.eecs.berkeley.edu/~necula/cil/).

Thanks,
Kihong

[time-1.7.c.zip](https://github.com/facebook/infer/files/614619/time-1.7.c.zip)

**Comment by akotulski** [comment] 2016-11-28 09:29
Thank you for reporting, I managed to reproduce the issue:
```
MacBook-Pro:Downloads akotulski$ infer --no-failures-allowed -- clang -c time-1.7.c
Capturing in make/cc mode...
Uncaught exception:
  
  (Unix.Unix_error "No such file or directory" realpath
   /usr/include/bits/types.h)

Raised at file "base/Utils.ml", line 616, characters 55-58
Called from file "clang/Capture.re", line 120, characters 9-45
Called from file "clang/Capture.re", line 185, characters 6-124
Called from file "list.ml", line 73, characters 12-15
Called from file "clang/ClangWrapper.re", line 102, characters 2-38
Called from file "clang/InferClang.re", line 14, characters 2-33
```

It looks like time-1.7.c was generated on another computer with different layout for system headers, but infer should be smart enough to deal with it.
Currently I'm overhauling this part of the system and will fix this bug, but it may take some time before it's fixed.

**Comment by akotulski** [comment] 2016-12-05 14:19
I committed fix in https://github.com/facebook/infer/commit/bd0f0cc7fcfe61e5c80a2ac91af1b94dc153584f

Note that infer doesn't really support running on preprocessed source code (other than "it shouldn't raise exceptions"), so I'm discouraging you from doing it if possible. Recent changes to our frontend broke this and it may break again in the future. This fix doesn't restore all functionalities there were before either and you'll need to pass extra option to `infer` (see below).

That being said, if you want to do that, remember to run infer with `--headers` option so that frontend translates everything from that file. Otherwise it won't translate anything. Everything includes all system headers which is not the case with default `infer` invocation.

Feel free to reopen if this doesn't work for you

**Closed by akotulski** 2016-12-05 14:19 UTC
Labels: bug, c

**Comment by evgzor** [comment] 2017-01-02 11:21
Hi, 

I have the same problem please c below:

evgzor$ infer -- xcodebuild -target CustomDatePicker -configuration Debug -sdk iphonesimulator
0.2.4
2017-01-02 14:08:11.428 xcodebuild[41219:131183] [MT] PluginLoading: Required plug-in compatibility UUID E0A62D1F-3C18-4D74-BFE5-A4167D643966 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/VVDocumenter-Xcode.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2017-01-02 14:08:11.428 xcodebuild[41219:131183] [MT] PluginLoading: Required plug-in compatibility UUID E0A62D1F-3C18-4D74-BFE5-A4167D643966 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/SCXcodeSwitchExpander.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2017-01-02 14:08:11.429 xcodebuild[41219:131183] [MT] PluginLoading: Required plug-in compatibility UUID E0A62D1F-3C18-4D74-BFE5-A4167D643966 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/ObjectGraph.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2017-01-02 14:08:11.429 xcodebuild[41219:131183] [MT] PluginLoading: Required plug-in compatibility UUID E0A62D1F-3C18-4D74-BFE5-A4167D643966 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/KSHObjcUML.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2017-01-02 14:08:11.429 xcodebuild[41219:131183] [MT] PluginLoading: Required plug-in compatibility UUID E0A62D1F-3C18-4D74-BFE5-A4167D643966 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/FuzzyAutocomplete.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2017-01-02 14:08:11.429 xcodebuild[41219:131183] [MT] PluginLoading: Required plug-in compatibility UUID E0A62D1F-3C18-4D74-BFE5-A4167D643966 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs
▸ Building CustomDatePicker/CustomDatePicker [Debug]
▸ Check Dependencies
▸ Precompiling CustomDatePicker/CustomDatePicker-Prefix.pch
▸ Compiling main.m
▸ Compiling AppDelegate.m
▸ Compiling ViewController.m
▸ Compiling CustomDatePicker.m
▸ Compiling CustomPickerView.m
▸ Linking CustomDatePicker
▸ Copying InfoPlist.strings
▸ Compiling ViewController_iPhone.xib
▸ Compiling ViewController_iPad.xib
▸ Compiling LaunchScreen.storyboard
▸ Processing CustomDatePicker-Info.plist
▸ Touching CustomDatePicker.app
▸ Signing build/Debug-iphonesimulator/CustomDatePicker.app
▸ Build Succeeded
Capturing using xcpretty...
Starting translating 5 files 
Uncaught exception:
  
  (Unix.Unix_error "No such file or directory" chdir
   "/Users/evgzor/Google\\ Drive/Projects/CustomDatePickerView/CustomDatePickerNoArc")

Called from file "base/Process.ml", line 111, characters 2-12
Called from file "backend/infer.ml", line 314, characters 2-30
Uncaught exception:
  
  (Unix.Unix_error "No such file or directory" chdir
   "/Users/evgzor/Google\\ Drive/Projects/CustomDatePickerView/CustomDatePickerNoArc")

Called from file "base/Process.ml", line 111, characters 2-12
Called from file "backend/infer.ml", line 314, characters 2-30
..Uncaught exception:
  
  (Unix.Unix_error "No such file or directory" chdir
   "/Users/evgzor/Google\\ Drive/Projects/CustomDatePickerView/CustomDatePickerNoArc")

Called from file "base/Process.ml", line 111, characters 2-12
Called from file "backend/infer.ml", line 314, characters 2-30
Uncaught exception:
  
  (Unix.Unix_error "No such file or directory" chdir
   "/Users/evgzor/Google\\ Drive/Projects/CustomDatePickerView/CustomDatePickerNoArc")

Called from file "base/Process.ml", line 111, characters 2-12
Called from file "backend/infer.ml", line 314, characters 2-30
..Uncaught exception:
  
  (Unix.Unix_error "No such file or directory" chdir
   "/Users/evgzor/Google\\ Drive/Projects/CustomDatePickerView/CustomDatePickerNoArc")

Called from file "base/Process.ml", line 111, characters 2-12
Called from file "backend/infer.ml", line 314, characters 2-30
..
Starting analysis...

legend:
  "F" analyzing a file
  "." analyzing a procedure

Found 0 source files in /Users/evgzor/Google Drive/Projects/CustomDatePickerView/CustomDatePickerNoArc/infer-out

Traceback (most recent call last):
  File "/usr/local/Cellar/infer/0.9.4.1/lib/infer/infer/bin/../lib/python/report.py", line 20, in <module>
    from inferlib import config, issues, utils
  File "/usr/local/Cellar/infer/0.9.4.1/lib/infer/infer/lib/python/inferlib/config.py", line 19, in <module>
    CODESET = locale.getlocale(locale.LC_CTYPE)[1]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 562, in getlocale
    return _parse_localename(localename)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 475, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8
** Error running the reporting script:
**   /usr/local/Cellar/infer/0.9.4.1/lib/infer/infer/bin/../lib/python/report.py --issues-csv /Users/evgzor/Google Drive/Projects/CustomDatePickerView/CustomDatePickerNoArc/infer-out/report.csv --issues-json /Users/evgzor/Google Drive/Projects/CustomDatePickerView/CustomDatePickerNoArc/infer-out/report.json --project-root /Users/evgzor/Google Drive/Projects/CustomDatePickerView/CustomDatePickerNoArc --results-dir /Users/evgzor/Google Drive/Projects/CustomDatePickerView/CustomDatePickerNoArc/infer-out
** See error above

U may try analyze my project : https://github.com/evgzor/CustomDatePickerView/tree/master/CustomDatePickerNoArc
