### ISSUE TITLE
Does infer support Swift?

### ISSUE THREAD

**Issue by baishikele** [facebook/infer#1273] opened 2020-06-01 03:03 UTC
Please make sure your issue is not addressed in the [FAQ](https://fbinfer.com/docs/support#troubleshooting).

Please include the following information:
- [ ] The version of infer from `infer --version`.
- [ ] Your operating system and version, for example "Debian 9", "MacOS High Sierra", whether you are using Docker, etc.
- [ ] Which command you ran, for example `infer -- make`.
- [ ] The full output in a paste, for instance a [gist](https://gist.github.com/).
- [ ] If possible, a minimal example to reproduce your problem (for instance, some code where
    infer reports incorrectly, together with the way you run infer to reproduce the incorrect
    report).

**Comment by jvillard** [comment] 2020-06-01 08:40
It does not. Closing as duplicate of #34.

**Closed by jvillard** 2020-06-01 08:40 UTC
