### ISSUE TITLE
Error in reporting line

### ISSUE THREAD

**Issue by achilleasxy** [facebook/infer#463] opened 2016-09-15 12:29 UTC
Infer reports a Null Dereference error for the the following code snippet.

```
@Override public String getSelectedProtocol(SSLSocket socket) {
      if (getAlpnSelectedProtocol == null) return null;
      if (!getAlpnSelectedProtocol.isSupported(socket)) return null;

      byte[] alpnResult = (byte[]) getAlpnSelectedProtocol.invokeWithoutCheckedException(socket);
      return alpnResult != null ? new String(alpnResult, Util.UTF_8) : null;
    }
```

Infer message:

> object context last assigned on line 261 could be null and is dereferenced by call to readFieldOrNull(...) at line 267

267 is the method header line.

**Comment by jeremydubreil** [comment] 2016-09-15 17:08
Hi @achilleasxy. I don't see either `readFieldOrNull` or an object named `context` in the code snippet. Does it exits somewhere else in the project ? In which case it could be an issue about reporting the errors in the right place.

**Comment by achilleasxy** [comment] 2016-09-19 09:39
Definitely a reporting error then. ````readFieldOrNull```` and ````context```` appear in the following methods which start on line 85 and 224 respectively:

````
public X509TrustManager trustManager(SSLSocketFactory sslSocketFactory) {
    // Attempt to get the trust manager from an OpenJDK socket factory. We attempt this on all
    // platforms in order to support Robolectric, which mixes classes from both Android and the
    // Oracle JDK. Note that we don't support HTTP/2 or other nice features on Robolectric.
    try {
      Class<?> sslContextClass = Class.forName("sun.security.ssl.SSLContextImpl");
      Object context = readFieldOrNull(sslSocketFactory, sslContextClass, "context");
      if (context == null) return null;
      return readFieldOrNull(context, X509TrustManager.class, "trustManager");
    } catch (ClassNotFoundException e) {
      return null;
    }
  }
```` 

````    
    @Override public X509TrustManager trustManager(SSLSocketFactory sslSocketFactory) {
      Object context = readFieldOrNull(sslSocketFactory, sslParametersClass, "sslParameters");
      if (context == null) {
        // If that didn't work, try the Google Play Services SSL provider before giving up. This
        // must be loaded by the SSLSocketFactory's class loader.
        try {
          Class<?> gmsSslParametersClass = Class.forName(
              "com.google.android.gms.org.conscrypt.SSLParametersImpl", false,
              sslSocketFactory.getClass().getClassLoader());
          context = readFieldOrNull(sslSocketFactory, gmsSslParametersClass, "sslParameters");
        } catch (ClassNotFoundException e) {
          return super.trustManager(sslSocketFactory);
        }
      }

      X509TrustManager x509TrustManager = readFieldOrNull(
          context, X509TrustManager.class, "x509TrustManager");
      if (x509TrustManager != null) return x509TrustManager;

      return readFieldOrNull(context, X509TrustManager.class, "trustManager");
    }
````

**Comment by jeremydubreil** [comment] 2016-09-22 17:41
Are the two definitions of `trustManager` in two different inner classes ?

**Comment by achilleasxy** [comment] 2016-09-27 08:13
Sorry for late response. Yes the first is in the public outer class and the second is in the static inner class that extends the outer class. It is from Okhttp version 3.2.0 in the Platform.java file.

**Comment by achilleasxy** [comment] 2016-10-13 09:44
Hi,
Is there any update on this issue?
I am not sure whether it is actually a true or false positive, but in any case it is incorrectly reported on a different line.

**Comment by jvillard** [comment] 2018-06-05 14:11
I cannot reproduce infer finding the bug mentioned originally using the latest infer and okhttp from today or from 25 Sep 2016, so cannot check if it's reported at the right line. Closing optimistically, please re-open with a concrete example.

**Closed by jvillard** 2018-06-05 14:11 UTC
Labels: java
