### ISSUE TITLE
build Android err

### ISSUE THREAD

**Issue by lailiaomm** [facebook/infer#391] opened 2016-07-06 11:00 UTC
Traceback (most recent call last):
  File "/usr/local/bin/infer", line 183, in <module>
    main()
  File "/usr/local/bin/infer", line 147, in main
    capture_exitcode = imported_module.gen_instance(args, cmd).capture()
  File "/usr/local/Cellar/infer/0.8.1/libexec/infer/lib/python/inferlib/capture/gradle.py", line 87, in capture
    cmds = self.get_infer_commands(util.get_build_output(self.build_cmd))
  File "/usr/local/Cellar/infer/0.8.1/libexec/infer/lib/python/inferlib/capture/util.py", line 27, in get_build_output
    return verbose_out_chars.split('\n')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 159: ordinal not in range(128)

**Comment by jvillard** [comment] 2016-07-06 11:06
This seems to be a duplicate of #387. Please update to the latest git version of Infer or try the fix suggested in #387 and reopen this issue if neither works.

**Closed by jvillard** 2016-07-06 11:06 UTC
