### ISSUE TITLE
infer 0.13.0 error

### ISSUE THREAD

**Issue by veryitman** [facebook/infer#815] opened 2017-11-19 07:42 UTC
I use command: 

`infer --keep-going --no-xcpretty -- xcodebuild -workspace my.xcworkspace -scheme myscheme -configuration Debug -sdk iphonesimulator`

It happends error:

```
Error backtrace:
Raised at file "integration/Driver.ml", line 297, characters 16-78
Called from file "integration/Driver.ml", line 176, characters 2-16
Called from file "backend/infer.ml", line 23, characters 2-36
Called from file "backend/infer.ml", line 106, characters 6-52
Uncaught error: ("InferModules__Driver.Infer_error(\"exited with code 65\")")
```

**Comment by jvillard** [comment] 2017-11-20 09:53
This looks like a duplicate of #810, please try the solution suggested there. If that doesn't work for you, please reopen this issue with more information. There should be more information about what failed in the build process in the console output.

**Closed by jvillard** 2017-11-20 09:53 UTC

**Comment by veryitman** [comment] 2017-11-22 13:11
*** clang: Caught sigint, time to die

** BUILD FAILED **


The following build commands failed:
	CompileC /Users/mark/Library/Developer/Xcode/DerivedData/Near-forfvyfvqglnckfhctqitpjdfqwa/Build/Intermediates.noindex/Near.build/Debug-iphonesimulator/WePlay.build/Objects-normal/x86_64/IDSKeyboardInputView.o Near/Classes/View/Keyboard/IDSKeyboardInputView.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Error backtrace:
Raised at file "integration/Driver.ml", line 297, characters 16-78
Called from file "integration/Driver.ml", line 176, characters 2-16
Called from file "backend/infer.ml", line 23, characters 2-36
Called from file "backend/infer.ml", line 106, characters 6-52
Uncaught error: ("InferModules__Driver.Infer_error(\"exited with code 65\")")

**Comment by veryitman** [comment] 2017-11-22 13:31
@jvillard It happened error all ways.
