### ISSUE TITLE
build infer v0.8.0 fail with custom-built gcc 5.3.0 on CentOS5.11

### ISSUE THREAD

**Issue by eldesh** [facebook/infer#322] opened 2016-03-28 09:00 UTC
In my environment, building infer 0.8.0 fail.
That seems to clang 3.8.0 is too strict ...?

environment:

```
GNU/Linux x86_64

- opam 1.2.2
- python 2.7.3
- gcc 5.3.0
- automake 1.14
- autoconf 2.69
```

build command:

```
CC=gcc-5.3.0 CXX=g++-5.3.0 ./build-infer.sh clang
```

log:

```
make[4]: Entering directory `/home/eldesh/download/infer/infer/models/cpp/src'
clang++ -c -w -std=c++11 c_src/glib.c -o c_src/glib_cxx.o
clang++ -c -w -std=c++11 c_src/infer_builtins.c -o c_src/infer_builtins_cxx.o
clang++ -c -w -std=c++11 c_src/libc_basic.c -o c_src/libc_basic_cxx.o
clang++ -c -w -std=c++11 c_src/math.c -o c_src/math_cxx.o
clang++ -c -w -std=c++11 c_src/wchar.c -o c_src/wchar_cxx.o
clang++ -c -w -std=c++11 c_src/wctype.c -o c_src/wctype_cxx.o
clang++ -c -w -std=c++11 c_src/xlib.c -o c_src/xlib_cxx.o
clang++ -c -w -std=c++11 shared_ptr.cpp -o shared_ptr.o
clang++ -c -w -std=c++11 type_info.cpp -o type_info.o
libc_basic.c:1216:5: error: redefinition of a 'extern inline' function 'stat' is not supported in C99 mode
int stat(const char* path, struct stat* buf) {
    ^
/usr/include/sys/stat.h:434:8: note: previous definition is here
__NTH (stat (__const char *__path, struct stat *__statbuf))
       ^
libc_basic.c:1481:5: error: redefinition of a 'extern inline' function 'fstat' is not supported in C99 mode
int fstat(int fildes, struct stat* buf) {
    ^
/usr/include/sys/stat.h:448:8: note: previous definition is here
__NTH (fstat (int __fd, struct stat *__statbuf))
       ^
c_src/libc_basic.c:1216:5: error: redefinition of 'stat'
int stat(const char* path, struct stat* buf) {
    ^
/usr/include/sys/stat.h:434:8: note: previous definition is here
__NTH (stat (__const char *__path, struct stat *__statbuf))
       ^
c_src/libc_basic.c:1481:5: error: redefinition of 'fstat'
int fstat(int fildes, struct stat* buf) {
    ^
/usr/include/sys/stat.h:448:8: note: previous definition is here
__NTH (fstat (int __fd, struct stat *__statbuf))
       ^
2 errors generated.
2 errors generated.
make[4]: *** [libc_basic.o] Error 1
make[4]: Leaving directory `/home/eldesh/download/infer/infer/models/c/src'
make[3]: *** [/home/eldesh/download/infer/infer/lib/specs/c_models] Error 2
make[3]: Leaving directory `/home/eldesh/download/infer/infer/models/c'
make[2]: *** [c] Error 2
make[2]: *** Waiting for unfinished jobs....
make[4]: *** [c_src/libc_basic_cxx.o] Error 1
make[4]: Leaving directory `/home/eldesh/download/infer/infer/models/cpp/src'
make[3]: *** [/home/eldesh/download/infer/infer/lib/specs/cpp_models] Error 2
make[3]: Leaving directory `/home/eldesh/download/infer/infer/models/cpp'
make[2]: *** [cpp] Error 2
make[2]: Leaving directory `/home/eldesh/download/infer/infer/models'
make[1]: *** [clang] Error 2
make[1]: Leaving directory `/home/eldesh/download/infer/infer'
make: *** [clang] Error 2

  compilation failure; you can try running

    make clean
    ./build-infer.sh clang
```

**Comment by akotulski** [comment] 2016-03-30 10:12
Thanks for reporting. I think this may be caused by the fact that your setup uses gcc 5.x and we haven't tested building infer in such environment much. In particular, I think that using C11 be default is at fault:
https://gcc.gnu.org/gcc-5/porting_to.html

To fix it, I need to be able to reproduce the problem first, which linux distribution are you using?

**Comment by eldesh** [comment] 2016-04-01 07:09
I worked on CentOS5.11 :cry: , so I compiled the new gcc-5.3.0 personally.

**Comment by akotulski** [comment] 2016-04-01 14:21
Ok, thanks. I'll try to reproduce it anyway, but I can't promise when the problem will be resolved.
For now, you can try to use gcc-4.9.x which is better tested and supported

**Comment by akotulski** [comment] 2016-04-01 15:31
I tried to build infer 0.8.0 on fedora23 which uses gcc-5.3.1 and it was successful, so it looks like it's not gcc-5.3 fault.

I have theory why it happens to you, but I it's very hard to reproduce for me (and unlikely to happen again). I think infer is still picking up headers from old gcc (centOS 5.11 default one) and those don't work well with infer. If that's the case, using gcc-4.9 might not help either.
If you are willing to change couple of lines in infer codebase, I should have patch for you to try (it would make infer pick up new headers)

**Comment by jvillard** [comment] 2018-06-05 12:36
Closing optimistically as infer's clang has been upgraded since. Please reopen if there is still an issue.

**Closed by jvillard** 2018-06-05 12:36 UTC
