### ISSUE TITLE
A false positive about null dereference check

### ISSUE THREAD

**Issue by Belle-PL** [facebook/infer#1465] opened 2021-07-02 07:44 UTC
1. Infer Version: 1.1.0

2. OS version: Ubuntu 20.04

3. Command:
> infer run -- javac *filename*.java
  infer run --pulse -- javac *filename*.java

(Their outputs are identical.)

4. Full Output:
```
Capturing in javac mode...
Found 1 source file to analyze in /home/rainyd4y/infer-out
1/1 [################################################################################] 100% 49.725ms

InferTesting.java:218: error: Null Dereference
  object returned by `name2score.get("Tom")` could be null and is dereferenced at line 218.
  216.               name2score.put("Tom", 90);
  217.           }
  218. >         name2score.put("Tom", name2score.get("Tom") + 10);
  219.       }
  220.

Found 1 issue
          Issue Type(ISSUED_TYPE_ID): #
  Null Dereference(NULL_DEREFERENCE): 1
```
5. Minimal Test Example
```java
public void testNullDereference() {
      HashMap<String, Integer> name2score = new HashMap<>();
      String str = "Tom";
      long bound = System.currentTimeMillis() + 1 - System.currentTimeMillis() - 1;
      if(bound == 0) {
          name2score.put("Tom", 90);
      }
      name2score.put("Tom", name2score.get("Tom") + 10);  // should not report a warning here
  }
```
However, we can modify the line 4:
```java
long bound = System.currentTimeMillis() - System.currentTimeMillis() + 1 - 1;
```
Then, the false positive can be removed.

**Comment by jvillard** [comment] 2021-08-05 16:55
Hi @Belle-PL, thank you for your report and the repro case. I think the issue is fixed in Pulse, at least in the current master. Running `infer --pulse-only -- javac issue1465.java` I get "no issues found" as expected. Closing.

**Closed by jvillard** 2021-08-05 16:55 UTC
