### ISSUE TITLE
Migrate Website to Docusaurus 2 Alpha

### ISSUE THREAD

**Issue by mishal23** [facebook/infer#1171] opened 2019-10-28 08:01 UTC
Hi there! The Docusaurus team is currently developing Docusaurus 2 and are almost done with an MVP that doesn't include translations and versioning features, which means there's feature parity with your website's current usage of Docusaurus.

Docusaurus 2 brings about many improvements:

- Client-side rendering with prerendering (site renders without JavaScript!)
- More flexible appearance - Customizable layouts, CSS modules, etc
- Embeddable interactive React components within markdown via MDX

I will be helping you migrate and be the POC throughout the migration process. Let me know what you think!

cc @yangshun @endiliey @wgao19

**Comment by jvillard** [comment] 2019-11-06 12:05
I am confused: the infer documentation does not use Docusaurus at the moment.

**Comment by yangshun** [comment] 2019-11-06 12:10
Hey @jvillard sorry, that was a template statement. In Infer's case, it will be a migration from the current static site generator (Jekyll?) to Docusaurus 2, skipping Docusaurus 1 entirely.

**Comment by jvillard** [comment] 2019-11-06 12:43
Nice! Let us know if you need anything from our side.

**Comment by imbsky** [comment] 2019-11-21 08:14
Can I take this?

**Comment by imbsky** [comment] 2019-11-21 11:05
Almost done!

**Comment by imbsky** [comment] 2019-11-21 13:10
Preview here!
https://build-nu-two.now.sh

**Comment by imbsky** [comment] 2019-11-21 13:11
Some content on the top page has been deleted, but I will add it if necessary. and Should I target the master branch when I submit PR? Or would you like to continue targeting the gh-pages branch?

**Comment by imbsky** [comment] 2019-11-21 13:16
https://github.com/imbsky/infer/tree/docusaurus

**Comment by yangshun** [comment] 2019-11-21 21:03
I'd leave that to the @jvillard to decide. Typically for D2 websites, the `gh-pages` branch should be for the `build` artifacts and the website code will be in a `website` directory within `master` branch.

@mishal23 just FYI that @imbsky has started work on it. @imbsky in future it'd be better to get green light from @mishal23 before taking over the task.

**Comment by imbsky** [comment] 2019-11-21 21:09
> Typically for D2 websites, the `gh-pages` branch should be for the build artifacts and the website code will be in a `website` directory within `master` branch.

I will open PR to the master branch.

> @imbsky in future it'd be better to get green light from @mishal23 before taking over the task.

Definitely!

**Comment by imbsky** [comment] 2019-11-22 11:07
I decided to use @uetchy's Math API instead of Katex. That's very good.

**Comment by imbsky** [comment] 2019-11-22 11:07
![image](https://user-images.githubusercontent.com/38746192/69421192-bd797b00-0d63-11ea-86f2-9a6db2231adf.png)

**Comment by jvillard** [comment] 2019-11-22 11:50
Having the website source on the master branch will be a lot more convenient, thanks!

**Comment by imbsky** [comment] 2019-11-22 21:06
Anytime. I love Infer and am happy to contribute to it even though it's not main Infer code!

**Comment by yangshun** [comment] 2019-11-22 21:20
Thank you @imbsky!

**Comment by imbsky** [comment] 2019-11-22 21:24
I'm adding some original top page content now, but it's strictly different from Jekyll, so it may look a little different.
<img alt="Screen Shot 2019-11-23 at 6 21 50" src="https://user-images.githubusercontent.com/38746192/69461302-95b50200-0db9-11ea-8818-0af73c7c86f6.png">

**Comment by imbsky** [comment] 2019-11-22 21:26
It takes a lot of additional code to fully reproduce an asciinema embed. It should be avoided considering maintainability. For example, it can become a liability the next time we upgrade to Docusaurus 3.

**Comment by imbsky** [comment] 2019-11-22 21:28
For that reason, We can't auto play it at the moment, is that okay?
![image](https://user-images.githubusercontent.com/38746192/69461623-4fac6e00-0dba-11ea-83bf-339372df6c1e.png)

**Comment by imbsky** [comment] 2019-11-22 21:56
WIP
![image](https://user-images.githubusercontent.com/38746192/69463164-4de4a980-0dbe-11ea-9d69-25f465f6426c.png)

**Comment by yangshun** [comment] 2019-11-22 21:57
@imbsky make a PR and we can review it. There should be ways to let ASCII cinema still work. See https://github.com/facebookresearch/hydra/blob/master/website/docs/tutorial/7_tab_completion.md for an example. You should just need to set `data-autoplay="true"` for the added script tag.

**Comment by imbsky** [comment] 2019-11-22 22:11
Autoplay still doesn't work...

**Comment by imbsky** [comment] 2019-11-22 22:12
But it's great because it doesn't open in a new tab.

**Comment by imbsky** [comment] 2019-11-22 22:51
Latest preview here!
https://build-9j1y8wnmo.now.sh

**Comment by imbsky** [comment] 2019-11-22 22:55
The mobile view in the "Who Uses Infer?" section has also been slightly improved!

**Comment by yangshun** [comment] 2019-11-23 00:31
I must say, it looks gorgeous :)

**Comment by imbsky** [comment] 2019-11-23 03:46
@jvillard We can install Infer via brew core even if we on Catalina (and Mojave), would you like to fix the install guide to avoid confusion?

**Comment by imbsky** [comment] 2019-11-24 13:37
I increased the font size because the font size in the code block was too small to see.

**Comment by imbsky** [comment] 2019-11-24 13:41
| Before                                                                                                                                                    | After                                                                                                                                                     |
| --------------------------------------------------------------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------- |
| <img alt="Screen Shot 2019-11-24 at 22 39 06" src="https://user-images.githubusercontent.com/38746192/69495537-62828800-0f0b-11ea-9f78-418818ded3f0.png"> | <img alt="Screen Shot 2019-11-24 at 22 39 52" src="https://user-images.githubusercontent.com/38746192/69495538-62828800-0f0b-11ea-9aac-ba665290fb91.png"> |

**Comment by jvillard** [comment] 2020-03-04 16:44
Docusaurus 2 website is up now, closing. :heart_eyes:

**Closed by jvillard** 2020-03-04 16:44 UTC
