### ISSUE TITLE
How does INFER do the points-to analysis for C code?

### ISSUE THREAD

**Issue by YizhuoZhai** [facebook/infer#1586] opened 2022-01-18 03:02 UTC
Hi, I'm trying the INFER on a small piece of C code:
``` c
struct coordinates {
    int x;
    int y;
};
void foo() {
    struct coordinates *c;
    c->y++;
}
```
Infer report no warnings here while c->y++ is obviously an uninitialized use. 
``` shell
$infer run  -- clang -c uninit.c 
Capturing in make/cc mode...
Found 1 source file to analyze in /infer-examples/infer-out
1/1 [################################################################################] 100% 63.67ms

  No issues found  
$ infer --version 
Infer version v1.1.0
Copyright 2009 - present Facebook. All Rights Reserved.
```
Therefore, I wonder how INFER deal with the pointer, and does INFER do the points-to analysis for C code?

**Comment by jvillard** [comment] 2022-01-19 18:09
The uninitialized value analysis is now part of the Pulse analysis, which isn't yet enabled by default so you need to run with `--pulse` or `--pulse-only`:

```
$ infer --pulse-only -- clang -c issue1586.c
issue1586.c:7: error: Uninitialized Value
  Pulse found a potential uninitialized value `c` being read on on line 7.
  5. void foo() {
  6.     struct coordinates *c;
  7.     c->y++;
         ^
  8. }


Found 1 issue
                      Issue Type(ISSUED_TYPE_ID): #
  Uninitialized Value(PULSE_UNINITIALIZED_VALUE): 1
```

**Comment by YizhuoZhai** [comment] 2022-01-20 00:34
> The uninitialized value analysis is now part of the Pulse analysis, which isn't yet enabled by default so you need to run with `--pulse` or `--pulse-only`:
> 
> ```
> $ infer --pulse-only -- clang -c issue1586.c
> issue1586.c:7: error: Uninitialized Value
>   Pulse found a potential uninitialized value `c` being read on on line 7.
>   5. void foo() {
>   6.     struct coordinates *c;
>   7.     c->y++;
>          ^
>   8. }
> 
> 
> Found 1 issue
>                       Issue Type(ISSUED_TYPE_ID): #
>   Uninitialized Value(PULSE_UNINITIALIZED_VALUE): 1
> ```

Thanks, Jules. But I cannot reproduce your result with the exact command, could you please help here? I use the docker provided in the repo.
``` shell
$infer --pulse-only -- clang -c  uninit.c 
Capturing in make/cc mode...
Found 1 source file to analyze in /infer-examples/infer-out
1/1 [################################################################################] 100% 72.055ms

  No issues found  
```

``` shell
$infer --pulse -- clang -c  uninit.c 
Capturing in make/cc mode...
Found 1 source file to analyze in /infer-examples/infer-out
1/1 [################################################################################] 100% 72.721ms

  No issues found  
```

I also wonder how Pulse detector does pointer analysis. Does it use the Andersen?

**Comment by jvillard** [comment] 2022-02-11 18:02
Closing this as the problem is fixed in the current main.

**Closed by jvillard** 2022-02-11 18:02 UTC

**Comment by YizhuoZhai** [comment] 2022-03-12 04:13
How about this piece of code then?

```C
void caller(arg) {
    int *p;
    int a = 0, b;
    if (arg) {
        p = &a;
    }
    else {
        p = &b;
    }
    if (*p++) {}; //an uninitialized use if arg equals to 0
}
```

```sh
$ infer --pulse --enable-issue-type PULSE_UNINITIALIZED_VALUE -- clang -c test.c
Capturing in make/cc mode...
Found 1 source file to analyze in /opt/infer-linux64-v1.1.0/test/alias/infer-out
1/1 [################################################################################] 100% 66.455ms

  No issues found  
```

**Comment by YizhuoZhai** [comment] 2022-03-12 04:15
Hi Jules:
Could you please check my latest comment?
https://github.com/facebook/infer/issues/1586
