### ISSUE TITLE
Unable to Install Infer.Kindly help

### ISSUE THREAD

**Issue by himgupta229** [facebook/infer#1480] opened 2021-08-06 10:17 UTC
I am trying to install infer on my system but unable to do so.
OS - Mac OS Big Sur (11.2.2)(20D80)
Chip - Apple M1
I tried using  three ways:

1. brew install infer. It gives error - 
`Error: infer: no bottle available!
You can try to install from source with:
  brew install --build-from-source infer
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for`
2. brew install --build-from-source infer
Got error - [https://gist.github.com/himgupta229/e991027cd27e7fde08faff6d633ee0d0]

**Comment by jvillard** [comment] 2021-08-06 12:37
Infer cannot be installed on M1 at the moment. I believe the only blocker is a crash in the parmap library https://github.com/rdicosmo/parmap/issues/103

Closing as duplicate of #1410, please comment there to discuss this issue.

**Closed by jvillard** 2021-08-06 12:37 UTC

**Comment by ChinaZeng** [comment] 2022-05-12 03:25
Is this problem solved please?

**Comment by mhashim6** [comment] 2022-11-08 12:53
If anyone is interested, we'll be maintaining current and upcoming infer binaries for Apple Silicon on [Instabug/infer](https://github.com/Instabug/infer/releases/tag/v1.1.0).
