### ISSUE TITLE
C false positive: strange nested free operation.

### ISSUE THREAD

**Issue by timdeegan** [facebook/infer#137] opened 2015-07-10 13:30 UTC
Seen under Infer 0.2.0 on Ubuntu 14.10 x86_64.

The strangest bug I've seen today -- it seems to depend on the complexity of the free_data() function
E.g., if I remove the line 'free(data->c)' it passes fine.

    #include <stdlib.h>
    #include <unistd.h>
    
    struct data
    {
        void *a, *b, *c;
        int fd;
    };
    
    static void
    free_data(struct data *data)
    {
        if (data)
        {
            if (data->fd != -1)
                close(data->fd);
            free(data->a);
            free(data->b);
            free(data->c);
            free(data);
        }
    }
    
    void f(void)
    {
        struct data *data;
        data = calloc(1, sizeof (struct data));

        /* False positive: this is reported as MEMORY_LEAK */

        free_data(data);
    }

**Comment by ddino** [comment] 2015-07-13 09:23
Thanks timdeegan, we will have a look at this.

**Comment by jvillard** [comment] 2016-04-20 17:11
it's actually a duplicate of #120

**Closed by jvillard** 2016-04-20 17:11 UTC
Labels: c, false-positive
